<?php
if (!defined('ABSPATH')) exit;
final class Orthocal_Admin {
    static function boot($file) {
        add_action('admin_post_orthocal_cache',function(){
            if(!current_user_can('manage_options'))wp_die('Недостаточно прав.');check_admin_referer('orthocal_cache');
            $action=sanitize_key($_POST['operation']??'');$message='';
            if($action==='data'){update_option('orthocal_cache_generation',wp_generate_uuid4(),false);$message='Кэш данных сброшен. Новые ответы будут получены при открытии календаря.';}
            elseif($action==='check'){Orthocal_Media_Cache::recheck();$message='Проверка файлов поставлена в очередь WordPress. Локальные картинки продолжают работать.';}
            elseif($action==='media'){$message=Orthocal_Media_Cache::clear()?'Локальные копии очищены. Нужные файлы загрузятся заново.':'Идёт обновление файлов. Повторите очистку позже.';}
            set_transient('orthocal_admin_notice_'.get_current_user_id(),$message,60);
            wp_safe_redirect(admin_url('options-general.php?page=orthocal&tab=cache'));exit;
        });
    }
    static function packs() {
        return ['ornamental'=>'Орнаментальные с надписью','dark'=>'Фотографические тёмные','bronze-medallions'=>'Бронзовые медальоны','jeweled-medallions'=>'Самоцветные медальоны','photographic-vignettes'=>'Фотографические виньетки','gold-oval-medallions'=>'Золотые овальные медальоны','minimal-dark'=>'Минималистичные пиктограммы','vintage-watercolor'=>'Винтажная акварель','light-watercolor'=>'Светлая акварель','sticker-outline'=>'Контурные наклейки','soft-illustration'=>'Мягкая иллюстрация','clean-illustration'=>'Чистая иллюстрация','blue-photo'=>'Фотореалистика — синяя','rustic-photo'=>'Фотореалистика — деревенская','copper-photo'=>'Фотореалистика — медная','gold-photo'=>'Фотореалистика — золотая'];
    }
    static function field($name,$label,$type='text',$choices=[],$help='') {
        $o=Orthocal_Plugin::options();$id='oc-setting-'.$name;$value=$o[$name]??'';
        echo '<div class="oc-admin-field"><label for="'.esc_attr($id).'">'.esc_html($label).'</label>';
        if($type==='select'){
            echo '<select id="'.$id.'" name="orthocal_options['.$name.']">';foreach($choices as $key=>$text)echo '<option value="'.esc_attr($key).'" '.selected($value,(string)$key,false).'>'.esc_html($text).'</option>';echo '</select>';
        }elseif($type==='checkbox')echo '<input id="'.$id.'" type="checkbox" name="orthocal_options['.$name.']" value="1" '.checked($value,'1',false).'>';
        else echo '<input id="'.$id.'" type="'.esc_attr($type).'" name="orthocal_options['.$name.']" value="'.esc_attr($type==='password'?'':$value).'"'.($type==='password'?' autocomplete="new-password"':'').'>';
        if($help)echo '<p class="description">'.esc_html($help).'</p>';echo '</div>';
    }
    static function page() {
        if(!current_user_can('manage_options'))return;
        $o=Orthocal_Plugin::options();$stats=Orthocal_Media_Cache::stats();
        $tabs=['connection'=>'Подключение','appearance'=>'Вид и поведение','content'=>'Содержание и картинки','cache'=>'Кэш и файлы','shortcodes'=>'Конструктор шорткодов','help'=>'Помощь'];
        $tab=sanitize_key($_GET['tab']??'connection');if(!isset($tabs[$tab]))$tab='connection';
        echo '<div class="wrap oc-admin" data-oc-admin data-active-tab="'.esc_attr($tab).'" data-endpoint="'.esc_url(rest_url('orthocal/v1/')).'"><header class="oc-admin-hero"><div><span>КАЛЕНДАРНАЯ МАСТЕРСКАЯ · '.esc_html(Orthocal_Plugin::VERSION).'</span><h1>Православный календарь</h1><p>Настройте один раз. Размещайте на сайте так, как удобно вашим посетителям.</p></div><div class="oc-admin-badge">'.($o['key']||defined('ORTHOCAL_API_KEY')?'Ключ задан':'Нужен API-ключ').'<small>'.$stats['count'].' локальных файлов · '.esc_html(size_format($stats['bytes'])).'</small></div></header>';
        $notice=get_transient('orthocal_admin_notice_'.get_current_user_id());if($notice){echo '<div class="notice notice-success"><p>'.esc_html($notice).'</p></div>';delete_transient('orthocal_admin_notice_'.get_current_user_id());}
        echo '<nav class="nav-tab-wrapper" aria-label="Разделы настроек">';foreach($tabs as $key=>$label)echo '<a class="nav-tab'.($key===$tab?' nav-tab-active':'').'" href="'.esc_url(admin_url('options-general.php?page=orthocal&tab='.$key)).'" data-oc-tab="'.$key.'">'.$label.'</a>';echo '</nav>';
        echo '<form action="options.php" method="post" id="oc-settings-form">';settings_fields('orthocal');
        echo '<section id="oc-panel-connection" data-oc-panel="connection" class="oc-admin-card"><h2>Два источника — один календарь на вашем сайте</h2><p>Праздники, посты и ссылки на чтения — API календаря. Библейские тексты — BibleDesktop.</p><div class="oc-admin-fields">';
        self::field('key','API-ключ календаря','password',[],Orthocal_Plugin::key()?'Ключ сохранён и не выводится в браузер. Оставьте поле пустым, чтобы сохранить его.':'Без ключа доступен только сегодняшний день по Europe/Berlin.');
        echo '<label><input type="checkbox" name="orthocal_options[clear_key]" value="1"> Удалить сохранённый ключ</label>';
        self::field('lang','Язык календаря','select',['ru'=>'Русский','cu'=>'Церковнославянский','de'=>'Немецкий','uk'=>'Украинский','pl'=>'Польский']);
        self::field('profile','Профиль поста','select',['typikon-strict'=>'Типикон','parish'=>'Приходской'],'Профиль подписывается в карточке дня.');
        self::field('translation','Предпочитаемый перевод Библии','text',[],'Укажите код из каталога ниже или оставьте пустым для выбора посетителем.');
        echo '<div><button type="button" class="button" data-oc-load-translations>Показать переводы BibleDesktop</button><select data-oc-admin-translations aria-label="Доступные переводы" hidden></select><p data-oc-admin-status role="status"></p></div></div><p>Часовой пояс сайта: <strong>'.esc_html(wp_timezone_string()).'</strong>. Меняется в общих настройках WordPress.</p><p><a href="'.esc_url(admin_url('options-general.php')).'">Открыть общие настройки</a></p>';
        $quota=get_option('orthocal_quota');if($quota)echo '<p>Остаток месячной квоты при последнем запросе: <strong>'.(int)$quota['remaining'].'</strong> · '.esc_html(wp_date('d.m.Y H:i',$quota['checked'])).'</p>';
        echo '</section><section id="oc-panel-appearance" data-oc-panel="appearance" class="oc-admin-card"><h2>Оформление и открытие содержимого</h2><div class="oc-admin-fields">';
        self::field('theme','Оформление','select',['book'=>'Книжное — тёплый фон','modern'=>'Современное — светлое','inherit'=>'Шрифты сайта']);self::field('accent','Акцентный цвет','color');
        self::field('open','При нажатии на дату','select',['inline'=>'Под календарём','modal'=>'Во всплывающем окне','page'=>'На отдельной странице']);
        self::field('reading_open','Библейский текст','select',['inline'=>'Раскрывать под ссылкой','modal'=>'Открывать во всплывающем окне']);
        echo '<div class="oc-admin-field"><label for="oc-day-page">Страница подробностей дня</label>';
        wp_dropdown_pages(['name'=>'orthocal_options[day_page]','id'=>'oc-day-page','selected'=>(int)$o['day_page'],'show_option_none'=>'Текущая страница','option_none_value'=>'0']);echo '<p class="description">Разместите на выбранной странице [orthocal_day]. Применяется к ссылкам и режиму «На отдельной странице».</p></div>';
        self::field('branding','Подпись над блоком','text',[],'Можно заменить названием прихода или оставить пустой.');
        foreach(['heading'=>'Показывать заголовок блока','compact'=>'Компактный вид','oldstyle'=>'Показывать дату по старому стилю'] as $name=>$label)self::field($name,$label,'checkbox');
        echo '</div></section><section id="oc-panel-content" data-oc-panel="content" class="oc-admin-card"><h2>Что показывать в карточке дня</h2><fieldset><legend>Разделы по умолчанию</legend>';
        foreach(['fasting'=>'Пост и трапеза','saints'=>'Праздники и памяти','readings'=>'Библейские чтения','texts'=>'Справочник богослужебных текстов','icons'=>'Место для икон'] as $value=>$label)echo '<label class="oc-admin-check"><input type="checkbox" name="orthocal_options[sections][]" value="'.$value.'" '.checked(in_array($value,explode(',',$o['sections']),true),true,false).'> '.$label.'</label>';
        echo '</fieldset><div class="oc-admin-fields">';self::field('images','Показывать картинки поста и знаки Типикона','checkbox');self::field('image_pack','Набор картинок поста','select',self::packs(),'Все 16 наборов берутся из нашего календаря. Скачиваются только используемые файлы.');
        self::field('icons','Включить место для будущих икон','checkbox',[],'Пока проверенного каталога нет, пустые рамки и случайные изображения не выводятся.');
        echo '</div><div class="oc-admin-note"><h3>Богослужебные тексты</h3><p>Тропари, кондаки, молитвы и величания доступны в справочнике календаря. Начальный корпус требует богослужебной редакционной проверки; автоматическое назначение по датам не выполняется. Акафисты относятся к будущей библиотеке BibleDesktop — её API пока не подключён.</p></div></section>';
        echo '<section id="oc-panel-cache" data-oc-panel="cache" class="oc-admin-card"><h2>Локальные файлы и обновления</h2><p>При первом обращении картинки сохраняются в uploads/orthocal-cache. Следующие посетители получают их с вашего сайта. Проверка ETag / Last-Modified скачивает новую версию только при изменении; без этих заголовков сравниваем содержимое.</p><div class="oc-admin-fields">';
        self::field('media_hours','Проверять картинки и шрифт','select',['6'=>'Раз в 6 часов','12'=>'Раз в 12 часов','24'=>'Раз в сутки','168'=>'Раз в неделю']);
        self::field('bible_hours','Хранить библейские ответы','select',['0'=>'Не хранить','1'=>'1 час','6'=>'6 часов','24'=>'1 сутки'],'Если BibleDesktop запрещает хранение, запрет источника имеет приоритет.');
        echo '</div><p><strong>'.$stats['count'].'</strong> файлов · <strong>'.esc_html(size_format($stats['bytes'])).'</strong> из 64 МБ. Календарные данные — до 5 минут согласно разрешению API. При сбое обновления картинок остаётся рабочая локальная копия.</p>';
        $error=get_option('orthocal_media_error');if($error)echo '<p class="notice notice-warning">'.esc_html($error).'</p>';
        $entries=Orthocal_Media_Cache::entries();$failed=array_filter($entries,static fn($m)=>!empty($m['error']));
        echo '<p>Файлов с ошибкой последней проверки: '.count($failed).'. Фоновая проверка запускается через WP-Cron при посещениях сайта.</p><p>Если используется CDN или полностраничный кэш, исключите страницы с календарём либо ограничьте их кэш пятью минутами.</p></section>';
        echo '<div data-oc-save>';submit_button('Сохранить настройки');echo '</div></form>';
        echo '<div data-oc-panel="cache" class="oc-admin-card"><h2>Обслуживание</h2><form action="'.esc_url(admin_url('admin-post.php')).'" method="post"><input type="hidden" name="action" value="orthocal_cache">';wp_nonce_field('orthocal_cache');
        foreach(['check'=>'Проверить обновления картинок','data'=>'Сбросить кэш данных','media'=>'Очистить локальные картинки'] as $operation=>$label)echo '<button class="button" name="operation" value="'.$operation.'">'.$label.'</button> ';echo '</form><p class="description">Операции касаются только кэша плагина. Медиа-библиотека сайта не затрагивается.</p></div>';
        self::generator();self::help();
        echo '<div data-oc-panel="connection" class="oc-admin-card"><h2>Проверка подключения</h2><form method="post">';wp_nonce_field('orthocal_check');submit_button('Проверить оба API','secondary','orthocal_check');echo '</form>';
        if(isset($_POST['orthocal_check'])){check_admin_referer('orthocal_check');foreach(['calendar','bible'] as $service){$value=Orthocal_Plugin::request($service,$service==='calendar'?'day':'translations',$service==='calendar'?['date'=>wp_date('Y-m-d'),'lang'=>$o['lang'],'profile'=>$o['profile']]:[]);echo '<p><strong>'.esc_html($service).':</strong> '.esc_html(is_wp_error($value)?$value->get_error_message():'Подключение работает').'</p>';}}
        echo '</div></div>';
    }
    static function generator() {
        echo '<section data-oc-panel="shortcodes" class="oc-admin-card"><h2>Соберите свой блок</h2><p>Выберите вид и параметры, скопируйте готовую строку в блок WordPress «Шорткод».</p><div class="oc-admin-fields"><label>Вид блока<select data-oc-build="mode">';foreach(Orthocal_Plugin::TITLES as $mode=>$title)echo '<option value="'.$mode.'">'.$title.'</option>';echo '</select></label>';
        foreach(['date'=>'Дата (пусто — сегодня)','year'=>'Год','month'=>'Месяц (1–12)','limit'=>'Количество (1–10)','tone'=>'Глас (1–8), только справочник','weekday'=>'День седмицы (0–6), только справочник'] as $name=>$label)echo '<label>'.$label.'<input data-oc-build="'.$name.'" type="'.($name==='date'?'date':'number').'"></label>';
        echo '<label>Раздел справочника<select data-oc-build="scope"><option value="">Все</option><option value="resurrection">Воскресные</option><option value="weekday">Дни седмицы</option><option value="common">Общие</option></select></label><label>ID конкретного текста<input data-oc-build="text_id" type="text"></label><label>Набор картинок<select data-oc-build="image_pack"><option value="">Настройка сайта</option>';
        foreach(self::packs() as $value=>$label)echo '<option value="'.$value.'">'.$label.'</option>';echo '</select></label>';
        foreach(['open'=>['Открытие дня',[''=>'Настройка сайта','inline'=>'Под блоком','modal'=>'В окне','page'=>'На странице']],'theme'=>['Тема',[''=>'Настройка сайта','book'=>'Книжная','modern'=>'Современная','inherit'=>'Сайта']],'compact'=>['Размер',[''=>'Настройка сайта','1'=>'Компактный','0'=>'Подробный']],'filter'=>['События',[''=>'Главные','twelve'=>'Пасха и двунадесятые','great'=>'Великие','memorial'=>'Поминальные','all'=>'Все']]] as $name=>[$label,$options]){echo '<label>'.$label.'<select data-oc-build="'.$name.'">';foreach($options as $value=>$text)echo '<option value="'.$value.'">'.$text.'</option>';echo '</select></label>';}
        echo '</div><label for="oc-generated-code">Готовый шорткод</label><textarea id="oc-generated-code" rows="3" readonly>[orthocal_today]</textarea><p><button type="button" class="button button-primary" data-oc-copy-code>Скопировать</button> <button type="button" class="button" data-oc-preview>Показать результат</button></p><p data-oc-generator-status role="status"></p><div data-oc-preview-slot></div></section>';
    }
    static function help() {
        $examples=['today'=>'[orthocal_today]','calendar'=>'[orthocal_calendar open="modal"]','month'=>'[orthocal_month compact="1"]','year'=>'[orthocal_year year="2027"]','day'=>'[orthocal_day date="2027-05-02"]','upcoming'=>'[orthocal_upcoming limit="5"]','readings'=>'[orthocal_readings reading_open="modal"]','fasting'=>'[orthocal_fasting image_pack="light-watercolor"]','saints'=>'[orthocal_saints]','feasts'=>'[orthocal_feasts filter="twelve" limit="10"]','memorial'=>'[orthocal_memorial limit="3"]','pascha'=>'[orthocal_pascha year="2027"]','fasts'=>'[orthocal_fasts year="2027"]','date'=>'[orthocal_date]','texts'=>'[orthocal_texts]','troparia'=>'[orthocal_troparia scope="resurrection" tone="1"]','kontakia'=>'[orthocal_kontakia scope="weekday" weekday="3"]','prayers'=>'[orthocal_prayers]','magnifications'=>'[orthocal_magnifications]'];
        echo '<section data-oc-panel="help" class="oc-admin-card"><h2>Помощь и готовые рецепты</h2><ol><li>Сохраните API-ключ во вкладке «Подключение».</li><li>Выберите оформление и поведение ссылок.</li><li>Добавьте Gutenberg-блок или скопируйте шорткод.</li><li>Для отдельной страницы дня разместите на ней [orthocal_day] и выберите её в настройках.</li></ol><label>Найти пример <input type="search" data-oc-help-search placeholder="Например: пост, месяц, чтения"></label><div class="oc-help-examples">';
        foreach($examples as $mode=>$code)echo '<article data-oc-help-item><h3>'.esc_html(Orthocal_Plugin::TITLES[$mode]).'</h3><code>'.esc_html($code).'</code><button type="button" class="button" data-oc-copy-example="'.esc_attr($code).'">Копировать</button></article>';
        echo '</div><h3>Общие параметры</h3><table class="widefat striped"><thead><tr><th>Параметр</th><th>Значения</th><th>Назначение</th></tr></thead><tbody>';
        foreach([['date','ГГГГ-ММ-ДД','Гражданская дата по новому стилю; без параметра — сегодня.'],['year / month','1900–2200 / 1–12','Период сетки.'],['open','inline / modal / page','Где открыть выбранный день.'],['reading_open','inline / modal','Где открыть библейский текст.'],['theme','book / modern / inherit','Оформление блока.'],['compact / oldstyle / heading / images','0 / 1','Плотность, старый стиль, заголовок, картинки.'],['sections','fasting,saints,readings,texts,icons','Состав подробного дня.'],['scope / tone / weekday','resurrection,weekday,common / 1–8 / 0–6','Фильтры справочника; не назначение службе дня.'],['text_id','Стабильный ID текста','Одна конкретная запись справочника.'],['image_pack','Код одного из 16 наборов','Картинки правила поста.'],['lang','ru / cu / de / uk / pl','Язык календаря, независимо от перевода Библии.'],['profile','typikon-strict / parish','Профиль поста.'],['filter / limit','main,twelve,great,memorial,all / 1–10','Ближайшие события; до 366 дней вперёд.']] as $row)echo '<tr><td><code>'.esc_html($row[0]).'</code></td><td>'.esc_html($row[1]).'</td><td>'.esc_html($row[2]).'</td></tr>';
        echo '</tbody></table><h3>Частые вопросы</h3>';
        foreach(['Почему не показывается месяц?'=>'Для месяца, года и произвольных дат нужен действующий ключ и обновлённый API календаря. Проверьте подключение.','Что происходит при замене картинки на сервере?'=>'При очередной проверке изменённый файл сохраняется под новым именем с хэшем. Браузер получит новую версию; при сбое останется старая рабочая копия.','Почему нет икон?'=>'Контракт места для икон подготовлен, но изображения не угадываются. Нужен проверенный каталог с привязками и атрибуцией.','Что означает ошибка чтения?'=>'В выбранном переводе не найден полный набор запрошенных стихов либо ссылка не разобрана. Исходная ссылка сохраняется, приблизительный текст не подставляется.','Можно ли использовать несколько блоков?'=>'Да. Каждый переключается независимо. Ссылка на конкретную дату применяется к календарным блокам страницы.','Что взять для боковой колонки?'=>'[orthocal_month compact="1" open="modal"] и [orthocal_upcoming limit="3"].','Откуда появятся тропари и акафисты?'=>'Тропари, кондаки, молитвы и величания получаются через справочный API календаря. Акафисты запланированы в BibleDesktop, их API пока не подключён. Автоматического назначения песнопений дню нет.'] as $question=>$answer)echo '<details><summary>'.esc_html($question).'</summary><p>'.esc_html($answer).'</p></details>';
        echo '<p data-oc-help-status role="status"></p></section>';
    }
}
