/** Editorial calendar translations, not a replacement for XML dates or ranks.
 * Ecclesiastical terminology: orthodoxe-kirche.de German Minaeon and
 * Sonstiges/heiligenkalender/heiligenkalender.html (consulted 2026-09-08).
 * Historical annotations are retained from our XML, not independently re-dated.
 * Exact complete keys only; no transliteration of arbitrary unknown records.
 */
export const GERMAN_COMMEMORATIONS: Readonly<Record<string, string>> = {
  'Прп. Антония Великого (356)': 'Ehrwürdiger Antonios der Große (356)',
  'Прп. Евфимия Великого (473)': 'Ehrwürdiger Euthymios der Große (473)',
  'Собор новомучеников и исповедников Церкви Русской': 'Synaxis der Neumärtyrer und Bekenner der Russischen Kirche',
  'Собор Вселенских учителей и святителей Василия Великого, Григория Богослова и Иоанна Златоустого': 'Synaxis der ökumenischen Lehrer und heiligen Hierarchen Basilios des Großen, Gregor des Theologen und Johannes Chrysostomos',
  'Вмч. Георгия Победоносца (303)': 'Hl. Großmärtyrer Georg der Siegesträger (303)',
  'Иверской иконы Божией Матери (второе обретение списка иконы 2012)': 'Iveron-Ikone der Gottesmutter (zweite Auffindung einer Abschrift der Ikone, 2012)',
  'Апостола и евангелиста Иоанна Богослова (98-117)': 'Hl. Apostel und Evangelist Johannes der Theologe (98–117)',
  'Мефодия (885) и Кирилла (869), учителей Словенских': 'Methodios (885) und Kyrill (869), Lehrer der Slawen',
  'Равноап. вел. кн. Владимира, во св. Крещении Василия (1015)': 'Hl. apostelgleicher Großfürst Wladimir, in der heiligen Taufe Basilios (1015)',
  'Обретение мощей прп. Серафима, Саровского чудотворца (1903)': 'Auffindung der Reliquien des hl. Seraphim, des Wundertäters von Sarov (1903)',
  'Пророка Илии (IX до Р.Х.)': 'Hl. Prophet Elias (IX. Jahrhundert vor Christi Geburt)',
  'Преставление апостола и евангелиста Иоанна Богослова (начало II)': 'Entschlafen des hl. Apostels und Evangelisten Johannes des Theologen (Anfang des II. Jahrhunderts)',
  'Свт. Иоанна Златоустого, архиеп. Константинопольского (407)': 'Hl. Johannes Chrysostomos, Erzbischof von Konstantinopel (407)',
  'Прп. Саввы Освященного (532)': 'Ehrwürdiger Sabbas der Geheiligte (532)',
  'Святителя Николая, архиепископа Мир Ликийских чудотворца (ок. 345)': 'Hl. Nikolaus, Erzbischof von Myra in Lykien, der Wundertäter (um 345)',
  'Собор всех преподобных и Богоносных отцев, во Святой Горе Афонской просиявших': 'Synaxis aller ehrwürdigen und gotttragenden Väter, die auf dem Heiligen Berg Athos erstrahlt sind',
  'Преставление (1833),второе обретение (1991) мощей прп. Серафима, Саровского чудотворца': 'Entschlafen (1833) und zweite Auffindung der Reliquien (1991) des hl. Seraphim, des Wundertäters von Sarov',
  'Свт. Филиппа, митр. Московского и всея России чудотворца (1569)': 'Hl. Philipp, Metropolit von Moskau und ganz Russland, der Wundertäter (1569)',
  'Свт. Феофана, Затворника Вышенского (1894)': 'Hl. Theophan, der Klausner von Wyscha (1894)',
  'Прп. Феодосия Великого, общих житий начальника (529)': 'Ehrwürdiger Theodosios der Große, Begründer des gemeinschaftlichen Mönchslebens (529)',
  'Равноап. Нины, просветительницы Грузии (335)': 'Hl. apostelgleiche Nina, Erleuchterin Georgiens (335)',
  'Блж. Ксении Петербургской (XIX)': 'Hl. selige Xenia von St. Petersburg (XIX. Jahrhundert)',
  'Свт. Григория Богослова, архиеп. Константинопольского (389)': 'Hl. Gregor der Theologe, Erzbischof von Konstantinopel (389)',
  'Перенесение мощей свт. Иоанна Златоуста (438)': 'Übertragung der Reliquien des hl. Johannes Chrysostomos (438)',
  'Иверской иконы Божией Матери (IX)': 'Iveron-Ikone der Gottesmutter (IX. Jahrhundert)',
  'Свт. Алексия, митр. Московского и всея России, чудотворца (1378)': 'Hl. Alexios, Metropolit von Moskau und ganz Russland, der Wundertäter (1378)',
  'Равноап. Кирилла, учителя Словенского (869)': 'Hl. apostelgleicher Kyrill, Lehrer der Slawen (869)',
  'Первое (IV) и второе (452) обретение главы Иоанна Предтечи': 'Erste (IV. Jahrhundert) und zweite (452) Auffindung des Hauptes Johannes des Vorläufers',
  'Иконы Божией матери, именуемой "Державная" (1917)': 'Ikone der Gottesmutter „Die Herrschende“ (1917)',
  'Свт. Мефодия, архиеп. Моравского (885)': 'Hl. Methodios, Erzbischof von Mähren (885)',
  'Прп. Зосимы, игумена Соловецкого (1478)': 'Ehrwürdiger Zosimas, Abt von Solowki (1478)',
  'Блж. Матроны Московской (1952)': 'Hl. selige Matrona von Moskau (1952)',
  'Апостола и евангелиста Марка (63)': 'Hl. Apostel und Evangelist Markus (63)',
  'Ап. Иакова Зеведеева (44)': 'Hl. Apostel Jakobus, Sohn des Zebedäus (44)',
  'Свт. Игнатия Брянчанинова, еп. Кавказского и Черноморского (1867)': 'Hl. Ignatios Brjantschaninow, Bischof des Kaukasus und des Schwarzmeergebiets (1867)',
  'Перенесение мощей блгв. князей Российских Бориса и Глеба, во святом Крещении Романа и Давида (1072 и 1115)': 'Übertragung der Reliquien der hl. rechtgläubigen russischen Fürsten Boris und Gleb, in der heiligen Taufe Roman und David (1072 und 1115)',
  'Прп. Феодосия, игумена Киево-Печерского (1074)': 'Ehrwürdiger Theodosios, Abt des Kiewer Höhlenklosters (1074)',
  'Перенесение мощей святителя и чудотворца Николая из Мир Ликийских в Бар (1087)': 'Übertragung der Reliquien des hl. Hierarchen und Wundertäters Nikolaus von Myra in Lykien nach Bari (1087)',
  'Апостола Симона Зилота (I)': 'Hl. Apostel Simon der Zelot (I. Jahrhundert)',
  'Прп. Корнилия, чудотворца Комельского (1537)': 'Ehrwürdiger Kornelios, der Wundertäter von Komel (1537)',
  'Блгвв. вел. кн. Димитрия Донского (1389) и вел. кн. Евдокии, в инокинях Евфросинии (1407)': 'Hl. rechtgläubiger Großfürst Dimitrij Donskoj (1389) und hl. rechtgläubige Großfürstin Eudokia, als Nonne Euphrosyne (1407)',
  'Обретение мощей свт. Алексия, митр. Московского, всея России чудотворца (1431)': 'Auffindung der Reliquien des hl. Alexios, Metropoliten von Moskau, des Wundertäters von ganz Russland (1431)',
  'Владимирской иконы Божией Матери (1521)': 'Wladimir-Ikone der Gottesmutter (1521)',
};
