// Finite explanatory labels from XML. This does not add prohibitions or make
// pastoral decisions. No unknown feast/person is translated by substitution.
const CONDITIONS: Record<string, [string,string,string,string]> = {
  'в Неделю мясопустную': ['am Sonntag des Fleischverzichts','въ недѣ́лю мѧсопꙋ́стнꙋю', "у м'ясопусну неділю", "w niedzielę mięsopustną"],
  'в течение Сырной седмицы (масленицы)': ['während der Käsewoche (Butterwoche)','въ тече́нїе сы́рныѧ седми́цы (ма́сленицы)', "протягом Сирної седмиці (масниці)", "w ciągu tygodnia serowego (maslenicy)"],
  'в Неделю сыропустную': ['am Sonntag des Käseverzichts','въ недѣ́лю сыропꙋ́стнꙋю', "у сиропусну неділю", "w niedzielę seropustną"],
  'накануне праздника Входа Господня в Иерусалим': ['am Vorabend des Einzugs des Herrn in Jerusalem','въ навече́рїе пра́здника Вхо́да Гдⷭ҇нѧ во І҆ерꙋсали́мъ', "напередодні свята Входу Господнього до Єрусалима", "w przeddzień święta Wjazdu Pańskiego do Jerozolimy"],
  'в продолжение Великого поста': ['während der Großen Fastenzeit','въ продолже́нїе Вели́кагѡ поста̀', "протягом Великого посту", "w ciągu Wielkiego Postu"],
  'накануне Светлого Христова Воскресения (Пасхи)': ['am Vorabend der lichten Auferstehung Christi (Pascha)','въ навече́рїе Свѣ́тлагѡ Хрⷭ҇то́ва Воскрⷭ҇нїѧ (Па́схи)', "напередодні Світлого Христового Воскресіння (Пасхи)", "w przeddzień Świetlistego Zmartwychwstania Chrystusa (Paschy)"],
  'в течение Пасхальной (Светлой) седмицы': ['während der Paschawoche (Lichten Woche)','въ тече́нїе Пасха́льныѧ (Свѣ́тлыѧ) седми́цы', "протягом Пасхальної (Світлої) седмиці", "w ciągu Tygodnia Paschalnego (Świetlistego)"],
  'накануне праздника Вознесения Господня': ['am Vorabend der Himmelfahrt des Herrn','въ навече́рїе пра́здника Вознесе́нїѧ Гдⷭ҇нѧ', "напередодні свята Вознесіння Господнього", "w przeddzień święta Wniebowstąpienia Pańskiego"],
  'накануне праздника Дня Святой Троицы (Пятидесятницы)': ['am Vorabend des Festes der Heiligen Dreifaltigkeit (Pfingsten)','въ навече́рїе пра́здника Днѐ Ст҃ы́ѧ Тро́ицы (Пѧтдесѧ́тницы)', "напередодні свята Дня Святої Трійці (П'ятдесятниці)", "w przeddzień święta Dnia Trójcy Świętej (Pięćdziesiątnicy)"],
  'в продолжение Святок': ['während der heiligen Tage nach Weihnachten','въ продолже́нїе Свѧ́токъ', "протягом Святок", "w ciągu świętych dni po Bożym Narodzeniu"],
  'накануне праздника Святого Богоявления (Крещения Господа Бога и Спаса нашего Иисуса Христа)': ['am Vorabend der heiligen Theophanie (Taufe unseres Herrn und Gottes und Erlösers Jesus Christus)','въ навече́рїе пра́здника Ст҃а́гѡ Бг҃оѧвле́нїѧ (Кр҃ще́нїѧ Гдⷭ҇а Бг҃а и҆ Сп҃са на́шегѡ І҆и҃са Хрⷭ҇та̀)', "напередодні свята Святого Богоявлення (Хрещення Господа Бога і Спаса нашого Ісуса Христа)", "w przeddzień święta Objawienia Pańskiego (Chrztu Pana Boga i Zbawiciela naszego Jezusa Chrystusa)"],
  'накануне праздника Сретения Господа Нашего Иисуса Христа': ['am Vorabend der Begegnung unseres Herrn Jesus Christus','въ навече́рїе пра́здника Срѣ́тенїѧ Гдⷭ҇а на́шегѡ І҆и҃са Хрⷭ҇та̀', "напередодні свята Стрітення Господа нашого Ісуса Христа", "w przeddzień święta Spotkania Pana naszego Jezusa Chrystusa"],
  'накануне праздника Благовещения Пресвятой Богородицы': ['am Vorabend der Verkündigung an die allheilige Gottesgebärerin','въ навече́рїе пра́здника Благовѣще́нїѧ Прест҃ы́ѧ Бг҃оро́дицы', "напередодні свята Благовіщення Пресвятої Богородиці", "w przeddzień święta Zwiastowania Przenajświętszej Bogurodzicy"],
  'накануне праздника Рождества честного славного Пророка, Предтечи и Крестителя Господня Иоанна': ['am Vorabend der Geburt des ehrwürdigen und ruhmreichen Propheten, Vorläufers und Täufers des Herrn Johannes','въ навече́рїе пра́здника Рождества̀ честна́гѡ сла́внагѡ Прⷪ҇ро́ка, Прⷣте́чи и҆ Крⷭ҇ти́телѧ Гдⷭ҇нѧ І҆ѡа́нна', "напередодні свята Різдва чесного славного Пророка, Предтечі і Хрестителя Господнього Іоанна", "w przeddzień święta Narodzenia czcigodnego chwalebnego Proroka, Poprzednika i Chrzciciela Pańskiego Jana"],
  'в продолжение Петрова (Апостольского) поста': ['während des Petrusfastens (Apostelfastens)','въ продолже́нїе Петро́ва (А҆по́стольскагѡ) поста̀', "протягом Петрового (Апостольського) посту", "w ciągu Postu Piotrowego (Apostolskiego)"],
  'накануне праздника Славных и всехвальных первоверховных апостолов Петра и Павла': ['am Vorabend des Festes der ruhmreichen und allgepriesenen Erstapostel Petrus und Paulus','въ навече́рїе пра́здника сла́вныхъ и҆ всехва́льныхъ первоверхо́вныхъ а҆пⷭ҇лъ Петра̀ и҆ Па́ѵла', "напередодні свята Славних і всехвальних першоверховних апостолів Петра і Павла", "w przeddzień święta Chwalebnych i godnych wszelkiej chwały pierwszych wśród apostołów Piotra i Pawła"],
  'накануне праздника Преображения Господа Бога и Спаса нашего Иисуса Христа': ['am Vorabend der Verklärung unseres Herrn und Gottes und Erlösers Jesus Christus','въ навече́рїе пра́здника Преѡбраже́нїѧ Гдⷭ҇а Бг҃а и҆ Сп҃са на́шегѡ І҆и҃са Хрⷭ҇та̀', "напередодні свята Преображення Господа Бога і Спаса нашого Ісуса Христа", "w przeddzień święta Przemienienia Pana Boga i Zbawiciela naszego Jezusa Chrystusa"],
  'в продолжение Успенского поста': ['während der Fastenzeit vor dem Entschlafen der Gottesgebärerin','въ продолже́нїе Оу҆спе́нскагѡ поста̀', "протягом Успенського посту", "w ciągu Postu przed Zaśnięciem Bogurodzicy"],
  'накануне праздника Успения Пресвятой Владычицы нашей Богородицы и Приснодевы Марии': ['am Vorabend des Entschlafens unserer allheiligen Herrin, der Gottesgebärerin und Immerjungfrau Maria','въ навече́рїе пра́здника Оу҆спе́нїѧ Прест҃ы́ѧ Влⷣчцы на́шеѧ Бг҃оро́дицы и҆ Приснодѣ́вы Марі́и', "напередодні свята Успіння Пресвятої Владичиці нашої Богородиці і Приснодіви Марії", "w przeddzień święta Zaśnięcia Przenajświętszej Władczyni naszej Bogurodzicy i zawsze Dziewicy Marii"],
  'накануне праздника Усекновения главы Пророка, Предтечи и Крестителя Господня Иоанна': ['am Vorabend der Enthauptung des Propheten, Vorläufers und Täufers des Herrn Johannes','въ навече́рїе пра́здника Оу҆сѣкнове́нїѧ главы̀ Прⷪ҇ро́ка, Прⷣте́чи и҆ Крⷭ҇ти́телѧ Гдⷭ҇нѧ І҆ѡа́нна', "напередодні свята Усікновення голови Пророка, Предтечі і Хрестителя Господнього Іоанна", "w przeddzień święta Ścięcia głowy Proroka, Poprzednika i Chrzciciela Pańskiego Jana"],
  'в день Усекновения главы Иоанна Предтечи': ['am Tag der Enthauptung Johannes des Vorläufers','въ де́нь Оу҆сѣкнове́нїѧ главы̀ І҆ѡа́нна Прⷣте́чи', "у день Усікновення голови Іоанна Предтечі", "w dniu Ścięcia głowy Jana Poprzednika"],
  'накануне праздника Рождества Пресвятой Владычицы нашей Богородицы и Приснодевы Марии': ['am Vorabend der Geburt unserer allheiligen Herrin, der Gottesgebärerin und Immerjungfrau Maria','въ навече́рїе пра́здника Рождества̀ Прест҃ы́ѧ Влⷣчцы на́шеѧ Бг҃оро́дицы и҆ Приснодѣ́вы Марі́и', "напередодні свята Різдва Пресвятої Владичиці нашої Богородиці і Приснодіви Марії", "w przeddzień święta Narodzenia Przenajświętszej Władczyni naszej Bogurodzicy i zawsze Dziewicy Marii"],
  'накануне праздника Воздвижения Честного и Животворящего Креста Господня': ['am Vorabend der Erhöhung des ehrwürdigen und lebenspendenden Kreuzes des Herrn','въ навече́рїе пра́здника Воздвиже́нїѧ Честна́гѡ и҆ Животворѧ́щагѡ Крⷭ҇та̀ Гдⷭ҇нѧ', "напередодні свята Воздвиження Чесного і Животворчого Хреста Господнього", "w przeddzień święta Podwyższenia Czcigodnego i Życiodajnego Krzyża Pańskiego"],
  'в день Воздвижения Креста Господня': ['am Tag der Erhöhung des Kreuzes des Herrn','въ де́нь Воздвиже́нїѧ Крⷭ҇та̀ Гдⷭ҇нѧ', "у день Воздвиження Хреста Господнього", "w dniu Podwyższenia Krzyża Pańskiego"],
  'накануне праздника Покрова Пресвятой Владычицы нашей Богородицы и Приснодевы Марии': ['am Vorabend des Schutzes unserer allheiligen Herrin, der Gottesgebärerin und Immerjungfrau Maria','въ навече́рїе пра́здника Покро́ва Прест҃ы́ѧ Влⷣчцы на́шеѧ Бг҃оро́дицы и҆ Приснодѣ́вы Марі́и', "напередодні свята Покрову Пресвятої Владичиці нашої Богородиці і Приснодіви Марії", "w przeddzień święta Opieki Przenajświętszej Władczyni naszej Bogurodzicy i zawsze Dziewicy Marii"],
  'накануне праздника Введения во храм Пресвятой Владычицы нашей Богородицы и Приснодевы Марии': ['am Vorabend des Einzugs unserer allheiligen Herrin, der Gottesgebärerin und Immerjungfrau Maria, in den Tempel','въ навече́рїе пра́здника Введе́нїѧ во хра́мъ Прест҃ы́ѧ Влⷣчцы на́шеѧ Бг҃оро́дицы и҆ Приснодѣ́вы Марі́и', "напередодні свята Введення до храму Пресвятої Владичиці нашої Богородиці і Приснодіви Марії", "w przeddzień święta Wprowadzenia do świątyni Przenajświętszej Władczyni naszej Bogurodzicy i zawsze Dziewicy Marii"],
  'в продолжение Рождественского (Филиппова) поста': ['während des Weihnachtsfastens (Philippusfastens)','въ продолже́нїе Рожде́ственскагѡ (Філі́ппова) поста̀', "протягом Різдвяного (Пилипового) посту", "w ciągu Postu Bożonarodzeniowego (Filipowego)"],
  'накануне праздника Рождества Господа и Спаса нашего Иисуса Христа': ['am Vorabend der Geburt unseres Herrn und Erlösers Jesus Christus','въ навече́рїе пра́здника Рождества̀ Гдⷭ҇а и҆ Сп҃са на́шегѡ І҆и҃са Хрⷭ҇та̀', "напередодні свята Різдва Господа і Спаса нашого Ісуса Христа", "w przeddzień święta Narodzenia Pana i Zbawiciela naszego Jezusa Chrystusa"],
  'накануне праздника Обрезания Господня': ['am Vorabend der Beschneidung des Herrn','въ навече́рїе пра́здника Обрѣ́занїѧ Гдⷭ҇нѧ', "напередодні свята Обрізання Господнього", "w przeddzień święta Obrzezania Pańskiego"],
};
export function localizeMarriageTitle(title:string, language:string):string|undefined {
  const prefix = 'Браковенчание не совершается ';
  if ((language!=='de'&&language!=='cu'&&language!=='uk'&&language!=='pl') || !title.startsWith(prefix)) return undefined;
  const key = title.slice(prefix.length);
  if (!Object.hasOwn(CONDITIONS,key)) return undefined;
  if (language === 'uk') return `Вінчання не звершується ${CONDITIONS[key]![2]}`;
  if (language === 'pl') return `Nie udziela się ślubu cerkiewnego ${CONDITIONS[key]![3]}`;
  return language==='de' ? `Die kirchliche Trauung wird ${CONDITIONS[key]![0]} nicht vollzogen`
    : `Браковѣнча́нїе не соверша́етсѧ ${CONDITIONS[key]![1]}`;
}
