/* Generated by scripts/build-decor-library.ts. */
import type { DecorLibraryItem } from "./decor-library";

export const DECOR_LIBRARY_ITEMS: readonly DecorLibraryItem[] = [
  {
    "id": "2407334",
    "label": "Густой цветочный угол",
    "category": "corners",
    "sourceId": "2407334",
    "source": "/assets/decor/items/2407334.svg",
    "aspectRatio": 1
  },
  {
    "id": "48407-01",
    "sourceId": "48407",
    "label": "Густой цветочный угол 1",
    "category": "corners",
    "source": "/assets/decor/items/48407-01.svg",
    "aspectRatio": 1.028388928317956
  },
  {
    "id": "48407-02",
    "sourceId": "48407",
    "label": "Густой цветочный угол 2",
    "category": "corners",
    "source": "/assets/decor/items/48407-02.svg",
    "aspectRatio": 1.0254777070063694
  },
  {
    "id": "2465406-01",
    "sourceId": "2465406",
    "label": "Линейный угол 1",
    "category": "corners",
    "source": "/assets/decor/items/2465406-01.svg",
    "aspectRatio": 1.0475613875058305
  },
  {
    "id": "2465406-02",
    "sourceId": "2465406",
    "label": "Линейный угол 2",
    "category": "corners",
    "source": "/assets/decor/items/2465406-02.svg",
    "aspectRatio": 1.0477668975400043
  },
  {
    "id": "2465406-03",
    "sourceId": "2465406",
    "label": "Линейный угол 3",
    "category": "corners",
    "source": "/assets/decor/items/2465406-03.svg",
    "aspectRatio": 1.0459130498661635
  },
  {
    "id": "2465406-04",
    "sourceId": "2465406",
    "label": "Линейный угол 4",
    "category": "corners",
    "source": "/assets/decor/items/2465406-04.svg",
    "aspectRatio": 1.0472858821801085
  },
  {
    "id": "2465361-01",
    "sourceId": "2465361",
    "label": "Резной угол A 1",
    "category": "corners",
    "source": "/assets/decor/items/2465361-01.svg",
    "aspectRatio": 1.0167198483439108
  },
  {
    "id": "2465361-02",
    "sourceId": "2465361",
    "label": "Резной угол A 2",
    "category": "corners",
    "source": "/assets/decor/items/2465361-02.svg",
    "aspectRatio": 1.0103609861775023
  },
  {
    "id": "2465361-03",
    "sourceId": "2465361",
    "label": "Резной угол A 3",
    "category": "corners",
    "source": "/assets/decor/items/2465361-03.svg",
    "aspectRatio": 1.017207606233396
  },
  {
    "id": "2465361-04",
    "sourceId": "2465361",
    "label": "Резной угол A 4",
    "category": "corners",
    "source": "/assets/decor/items/2465361-04.svg",
    "aspectRatio": 1.0136751814319331
  },
  {
    "id": "2465387-01",
    "sourceId": "2465387",
    "label": "Резной угол B 1",
    "category": "corners",
    "source": "/assets/decor/items/2465387-01.svg",
    "aspectRatio": 0.969373740853994
  },
  {
    "id": "2465387-02",
    "sourceId": "2465387",
    "label": "Резной угол B 2",
    "category": "corners",
    "source": "/assets/decor/items/2465387-02.svg",
    "aspectRatio": 1.0306005858531515
  },
  {
    "id": "2465387-03",
    "sourceId": "2465387",
    "label": "Резной угол B 3",
    "category": "corners",
    "source": "/assets/decor/items/2465387-03.svg",
    "aspectRatio": 0.9695974413972727
  },
  {
    "id": "2465387-04",
    "sourceId": "2465387",
    "label": "Резной угол B 4",
    "category": "corners",
    "source": "/assets/decor/items/2465387-04.svg",
    "aspectRatio": 1.02960769800148
  },
  {
    "id": "2407434",
    "label": "Тонкий угловой завиток",
    "category": "corners",
    "sourceId": "2407434",
    "source": "/assets/decor/items/2407434.svg",
    "aspectRatio": 1.5005861664712778
  },
  {
    "id": "2479760-01",
    "sourceId": "2479760",
    "label": "Тонкий цветочный угол 1",
    "category": "corners",
    "source": "/assets/decor/items/2479760-01.svg",
    "aspectRatio": 0.930571522602576
  },
  {
    "id": "2479760-02",
    "sourceId": "2479760",
    "label": "Тонкий цветочный угол 2",
    "category": "corners",
    "source": "/assets/decor/items/2479760-02.svg",
    "aspectRatio": 0.928542768392911
  },
  {
    "id": "2479760-03",
    "sourceId": "2479760",
    "label": "Тонкий цветочный угол 3",
    "category": "corners",
    "source": "/assets/decor/items/2479760-03.svg",
    "aspectRatio": 1.0093926337667591
  },
  {
    "id": "2479760-04",
    "sourceId": "2479760",
    "label": "Тонкий цветочный угол 4",
    "category": "corners",
    "source": "/assets/decor/items/2479760-04.svg",
    "aspectRatio": 1.0108365582127863
  },
  {
    "id": "2407437",
    "label": "Угловой листовой завиток",
    "category": "corners",
    "sourceId": "2407437",
    "source": "/assets/decor/items/2407437.svg",
    "aspectRatio": 1
  },
  {
    "id": "42840",
    "label": "Угловой растительный узор",
    "category": "corners",
    "sourceId": "42840",
    "source": "/assets/decor/items/42840.svg",
    "aspectRatio": 1.062240663900415
  },
  {
    "id": "48945",
    "label": "Угловой растительный узор, вариант",
    "category": "corners",
    "sourceId": "48945",
    "source": "/assets/decor/items/48945.svg",
    "aspectRatio": 1.06312292358804
  },
  {
    "id": "2407426",
    "label": "Угол с лентой и листом",
    "category": "corners",
    "sourceId": "2407426",
    "source": "/assets/decor/items/2407426.svg",
    "aspectRatio": 1
  },
  {
    "id": "770506-01",
    "sourceId": "770506",
    "label": "Угол с розеткой 1",
    "category": "corners",
    "source": "/assets/decor/items/770506-01.svg",
    "aspectRatio": 1.5659574468085107
  },
  {
    "id": "770506-02",
    "sourceId": "770506",
    "label": "Угол с розеткой 2",
    "category": "corners",
    "source": "/assets/decor/items/770506-02.svg",
    "aspectRatio": 1.5659574468085107
  },
  {
    "id": "1750894",
    "label": "Цветочный бордюр",
    "category": "corners",
    "sourceId": "1750894",
    "source": "/assets/decor/items/1750894.svg",
    "aspectRatio": 1.1500449236298294
  },
  {
    "id": "2859012-01",
    "sourceId": "2859012",
    "label": "Ягодный угол 1",
    "category": "corners",
    "source": "/assets/decor/items/2859012-01.svg",
    "aspectRatio": 1.3767841891231682
  },
  {
    "id": "2859012-02",
    "sourceId": "2859012",
    "label": "Ягодный угол 2",
    "category": "corners",
    "source": "/assets/decor/items/2859012-02.svg",
    "aspectRatio": 1.3770185076487422
  },
  {
    "id": "2859012-03",
    "sourceId": "2859012",
    "label": "Ягодный угол 3",
    "category": "corners",
    "source": "/assets/decor/items/2859012-03.svg",
    "aspectRatio": 1.3771068707746865
  },
  {
    "id": "2859012-04",
    "sourceId": "2859012",
    "label": "Ягодный угол 4",
    "category": "corners",
    "source": "/assets/decor/items/2859012-04.svg",
    "aspectRatio": 1.3770185076487425
  },
  {
    "id": "2465163-01",
    "sourceId": "2465163",
    "label": "Горизонтальный разделитель 1",
    "category": "dividers",
    "source": "/assets/decor/items/2465163-01.svg",
    "aspectRatio": 5.207357241092376
  },
  {
    "id": "2465163-02",
    "sourceId": "2465163",
    "label": "Горизонтальный разделитель 2",
    "category": "dividers",
    "source": "/assets/decor/items/2465163-02.svg",
    "aspectRatio": 7.948549848676025
  },
  {
    "id": "2465163-03",
    "sourceId": "2465163",
    "label": "Горизонтальный разделитель 3",
    "category": "dividers",
    "source": "/assets/decor/items/2465163-03.svg",
    "aspectRatio": 5.840829482673516
  },
  {
    "id": "2465163-04",
    "sourceId": "2465163",
    "label": "Горизонтальный разделитель 4",
    "category": "dividers",
    "source": "/assets/decor/items/2465163-04.svg",
    "aspectRatio": 8.06734639119936
  },
  {
    "id": "2465163-05",
    "sourceId": "2465163",
    "label": "Горизонтальный разделитель 5",
    "category": "dividers",
    "source": "/assets/decor/items/2465163-05.svg",
    "aspectRatio": 7.909862960818376
  },
  {
    "id": "2465163-06",
    "sourceId": "2465163",
    "label": "Горизонтальный разделитель 6",
    "category": "dividers",
    "source": "/assets/decor/items/2465163-06.svg",
    "aspectRatio": 6.488165041130627
  },
  {
    "id": "2465163-07",
    "sourceId": "2465163",
    "label": "Горизонтальный разделитель 7",
    "category": "dividers",
    "source": "/assets/decor/items/2465163-07.svg",
    "aspectRatio": 6.9046815689582415
  },
  {
    "id": "2465163-08",
    "sourceId": "2465163",
    "label": "Горизонтальный разделитель 8",
    "category": "dividers",
    "source": "/assets/decor/items/2465163-08.svg",
    "aspectRatio": 3.971698113207545
  },
  {
    "id": "782469-01",
    "sourceId": "782469",
    "label": "Классический разделитель 1",
    "category": "dividers",
    "source": "/assets/decor/items/782469-01.svg",
    "aspectRatio": 1.747801565513151
  },
  {
    "id": "782469-02",
    "sourceId": "782469",
    "label": "Классический разделитель 2",
    "category": "dividers",
    "source": "/assets/decor/items/782469-02.svg",
    "aspectRatio": 1.7477436060652494
  },
  {
    "id": "782469-03",
    "sourceId": "782469",
    "label": "Классический разделитель 3",
    "category": "dividers",
    "source": "/assets/decor/items/782469-03.svg",
    "aspectRatio": 2.452900661343934
  },
  {
    "id": "782469-04",
    "sourceId": "782469",
    "label": "Классический разделитель 4",
    "category": "dividers",
    "source": "/assets/decor/items/782469-04.svg",
    "aspectRatio": 2.8001464233932927
  },
  {
    "id": "782469-05",
    "sourceId": "782469",
    "label": "Классический разделитель 5",
    "category": "dividers",
    "source": "/assets/decor/items/782469-05.svg",
    "aspectRatio": 2.8015730832239596
  },
  {
    "id": "43842-01",
    "sourceId": "43842",
    "label": "Парный разделитель 1",
    "category": "dividers",
    "source": "/assets/decor/items/43842-01.svg",
    "aspectRatio": 2.103802589562094
  },
  {
    "id": "43842-02",
    "sourceId": "43842",
    "label": "Парный разделитель 2",
    "category": "dividers",
    "source": "/assets/decor/items/43842-02.svg",
    "aspectRatio": 2.103802589562094
  },
  {
    "id": "1751088",
    "label": "Цветочный разделитель",
    "category": "dividers",
    "sourceId": "1751088",
    "source": "/assets/decor/items/1751088.svg",
    "aspectRatio": 2
  },
  {
    "id": "2773448",
    "label": "Гильошная рамка",
    "category": "frames",
    "sourceId": "2773448",
    "source": "/assets/decor/items/2773448.svg",
    "aspectRatio": 1
  },
  {
    "id": "1210491",
    "label": "Густая прямоугольная рамка",
    "category": "frames",
    "sourceId": "1210491",
    "source": "/assets/decor/items/1210491.svg",
    "aspectRatio": 0.66640625
  },
  {
    "id": "1191028",
    "label": "Классическая квадратная рамка",
    "category": "frames",
    "sourceId": "1191028",
    "source": "/assets/decor/items/1191028.svg",
    "aspectRatio": 1
  },
  {
    "id": "1301811",
    "label": "Классическая рамка, вариант",
    "category": "frames",
    "sourceId": "1301811",
    "source": "/assets/decor/items/1301811.svg",
    "aspectRatio": 1.0587262200165426
  },
  {
    "id": "1321370",
    "label": "Лиственная квадратная рамка",
    "category": "frames",
    "sourceId": "1321370",
    "source": "/assets/decor/items/1321370.svg",
    "aspectRatio": 1
  },
  {
    "id": "2800269",
    "label": "Овальная растительная рамка",
    "category": "frames",
    "sourceId": "2800269",
    "source": "/assets/decor/items/2800269.svg",
    "aspectRatio": 0.95859375
  },
  {
    "id": "1781465",
    "label": "Орнаментальная квадратная рамка",
    "category": "frames",
    "sourceId": "1781465",
    "source": "/assets/decor/items/1781465.svg",
    "aspectRatio": 1
  },
  {
    "id": "322018",
    "label": "Рамка с пасхальными яйцами",
    "category": "frames",
    "sourceId": "322018",
    "source": "/assets/decor/items/322018.svg",
    "aspectRatio": 1.336116910229645
  },
  {
    "id": "303550",
    "label": "Рамка с плашкой и цветами",
    "category": "frames",
    "sourceId": "303550",
    "source": "/assets/decor/items/303550.svg",
    "aspectRatio": 0.8953125
  },
  {
    "id": "2031234",
    "label": "Рамка с раздельными украшениями",
    "category": "frames",
    "sourceId": "2031234",
    "source": "/assets/decor/items/2031234.svg",
    "aspectRatio": 1
  },
  {
    "id": "669764",
    "label": "Скруглённая рамка",
    "category": "frames",
    "sourceId": "669764",
    "source": "/assets/decor/items/669764.svg",
    "aspectRatio": 1.415929203539823
  },
  {
    "id": "669760",
    "label": "Скруглённая рамка с цветком",
    "category": "frames",
    "sourceId": "669760",
    "source": "/assets/decor/items/669760.svg",
    "aspectRatio": 1.415929203539823
  },
  {
    "id": "1781625",
    "label": "Тонкая линейная рамка",
    "category": "frames",
    "sourceId": "1781625",
    "source": "/assets/decor/items/1781625.svg",
    "aspectRatio": 1
  },
  {
    "id": "1689760",
    "label": "Тонкая рамка с завитками",
    "category": "frames",
    "sourceId": "1689760",
    "source": "/assets/decor/items/1689760.svg",
    "aspectRatio": 1
  },
  {
    "id": "332881",
    "label": "Тонкая цветочная рамка",
    "category": "frames",
    "sourceId": "332881",
    "source": "/assets/decor/items/332881.svg",
    "aspectRatio": 1.7777777777777777
  },
  {
    "id": "1321373",
    "label": "Узорная квадратная рамка",
    "category": "frames",
    "sourceId": "1321373",
    "source": "/assets/decor/items/1321373.svg",
    "aspectRatio": 1
  },
  {
    "id": "1210506",
    "label": "Фигурная прямоугольная рамка",
    "category": "frames",
    "sourceId": "1210506",
    "source": "/assets/decor/items/1210506.svg",
    "aspectRatio": 0.66640625
  },
  {
    "id": "1237902",
    "label": "Фоторамка с цветами",
    "category": "frames",
    "sourceId": "1237902",
    "source": "/assets/decor/items/1237902.svg",
    "aspectRatio": 1
  },
  {
    "id": "2479757",
    "label": "Цветочная прямоугольная рамка",
    "category": "frames",
    "sourceId": "2479757",
    "source": "/assets/decor/items/2479757.svg",
    "aspectRatio": 1.415929203539823
  },
  {
    "id": "334674",
    "label": "Цветочная рамка с открытыми сторонами",
    "category": "frames",
    "sourceId": "334674",
    "source": "/assets/decor/items/334674.svg",
    "aspectRatio": 1.7777777777777777
  },
  {
    "id": "2465064-01",
    "sourceId": "2465064",
    "label": "Геральдический флерон A 1",
    "category": "ornaments",
    "source": "/assets/decor/items/2465064-01.svg",
    "aspectRatio": 0.9705440818151048
  },
  {
    "id": "2465064-02",
    "sourceId": "2465064",
    "label": "Геральдический флерон A 2",
    "category": "ornaments",
    "source": "/assets/decor/items/2465064-02.svg",
    "aspectRatio": 1.0048210257620391
  },
  {
    "id": "2465064-03",
    "sourceId": "2465064",
    "label": "Геральдический флерон A 3",
    "category": "ornaments",
    "source": "/assets/decor/items/2465064-03.svg",
    "aspectRatio": 0.8466989414234962
  },
  {
    "id": "2465064-04",
    "sourceId": "2465064",
    "label": "Геральдический флерон A 4",
    "category": "ornaments",
    "source": "/assets/decor/items/2465064-04.svg",
    "aspectRatio": 1.362737243417963
  },
  {
    "id": "2465064-05",
    "sourceId": "2465064",
    "label": "Геральдический флерон A 5",
    "category": "ornaments",
    "source": "/assets/decor/items/2465064-05.svg",
    "aspectRatio": 1.3012347211019422
  },
  {
    "id": "2465064-06",
    "sourceId": "2465064",
    "label": "Геральдический флерон A 6",
    "category": "ornaments",
    "source": "/assets/decor/items/2465064-06.svg",
    "aspectRatio": 1.5352075188024024
  },
  {
    "id": "2465110-01",
    "sourceId": "2465110",
    "label": "Геральдический флерон B 1",
    "category": "ornaments",
    "source": "/assets/decor/items/2465110-01.svg",
    "aspectRatio": 0.9680221163169732
  },
  {
    "id": "2465110-02",
    "sourceId": "2465110",
    "label": "Геральдический флерон B 2",
    "category": "ornaments",
    "source": "/assets/decor/items/2465110-02.svg",
    "aspectRatio": 1.0048210257620391
  },
  {
    "id": "2465110-03",
    "sourceId": "2465110",
    "label": "Геральдический флерон B 3",
    "category": "ornaments",
    "source": "/assets/decor/items/2465110-03.svg",
    "aspectRatio": 0.8467783514512487
  },
  {
    "id": "2465110-04",
    "sourceId": "2465110",
    "label": "Геральдический флерон B 4",
    "category": "ornaments",
    "source": "/assets/decor/items/2465110-04.svg",
    "aspectRatio": 1.361182030229006
  },
  {
    "id": "2465110-05",
    "sourceId": "2465110",
    "label": "Геральдический флерон B 5",
    "category": "ornaments",
    "source": "/assets/decor/items/2465110-05.svg",
    "aspectRatio": 1.3024493746277548
  },
  {
    "id": "2465110-06",
    "sourceId": "2465110",
    "label": "Геральдический флерон B 6",
    "category": "ornaments",
    "source": "/assets/decor/items/2465110-06.svg",
    "aspectRatio": 1.5354877430808869
  },
  {
    "id": "2031361",
    "label": "Декоративный картуш",
    "category": "ornaments",
    "sourceId": "2031361",
    "source": "/assets/decor/items/2031361.svg",
    "aspectRatio": 1.8104667609618104
  },
  {
    "id": "42367",
    "label": "Каллиграфический завиток",
    "category": "ornaments",
    "sourceId": "42367",
    "source": "/assets/decor/items/42367.svg",
    "aspectRatio": 1.3305613305613306
  },
  {
    "id": "2457091-01",
    "sourceId": "2457091",
    "label": "Каллиграфический элемент 1",
    "category": "ornaments",
    "source": "/assets/decor/items/2457091-01.svg",
    "aspectRatio": 0.9344960288217473
  },
  {
    "id": "2457091-02",
    "sourceId": "2457091",
    "label": "Каллиграфический элемент 2",
    "category": "ornaments",
    "source": "/assets/decor/items/2457091-02.svg",
    "aspectRatio": 1.1276646139270488
  },
  {
    "id": "2457091-03",
    "sourceId": "2457091",
    "label": "Каллиграфический элемент 3",
    "category": "ornaments",
    "source": "/assets/decor/items/2457091-03.svg",
    "aspectRatio": 1.0417246175243393
  },
  {
    "id": "2457091-04",
    "sourceId": "2457091",
    "label": "Каллиграфический элемент 4",
    "category": "ornaments",
    "source": "/assets/decor/items/2457091-04.svg",
    "aspectRatio": 1.3048780487804879
  },
  {
    "id": "2457091-05",
    "sourceId": "2457091",
    "label": "Каллиграфический элемент 5",
    "category": "ornaments",
    "source": "/assets/decor/items/2457091-05.svg",
    "aspectRatio": 1.670748677984971
  },
  {
    "id": "2407423",
    "label": "Свободный цветочный завиток",
    "category": "ornaments",
    "sourceId": "2407423",
    "source": "/assets/decor/items/2407423.svg",
    "aspectRatio": 1
  },
  {
    "id": "2465156-01",
    "sourceId": "2465156",
    "label": "Симметричный флерон 1",
    "category": "ornaments",
    "source": "/assets/decor/items/2465156-01.svg",
    "aspectRatio": 1.6010998848957665
  },
  {
    "id": "2465156-02",
    "sourceId": "2465156",
    "label": "Симметричный флерон 2",
    "category": "ornaments",
    "source": "/assets/decor/items/2465156-02.svg",
    "aspectRatio": 1.5970149253731345
  },
  {
    "id": "2465156-03",
    "sourceId": "2465156",
    "label": "Симметричный флерон 3",
    "category": "ornaments",
    "source": "/assets/decor/items/2465156-03.svg",
    "aspectRatio": 1.0730709152603763
  },
  {
    "id": "2479754-01",
    "sourceId": "2479754",
    "label": "Цветочный акцент 1",
    "category": "ornaments",
    "source": "/assets/decor/items/2479754-01.svg",
    "aspectRatio": 3.329798951924254
  },
  {
    "id": "2479754-02",
    "sourceId": "2479754",
    "label": "Цветочный акцент 2",
    "category": "ornaments",
    "source": "/assets/decor/items/2479754-02.svg",
    "aspectRatio": 1.0081799164271292
  },
  {
    "id": "2028308",
    "label": "Образ святителя",
    "category": "religious",
    "sourceId": "2028308",
    "source": "/assets/decor/items/2028308.svg",
    "aspectRatio": 0.73046875
  },
  {
    "id": "2027568",
    "label": "Православные храмы",
    "category": "religious",
    "sourceId": "2027568",
    "source": "/assets/decor/items/2027568.svg",
    "aspectRatio": 0.9609375
  },
  {
    "id": "2023289",
    "label": "Святой с детьми",
    "category": "religious",
    "sourceId": "2023289",
    "source": "/assets/decor/items/2023289.svg",
    "aspectRatio": 0.7265625
  },
  {
    "id": "36238",
    "label": "Колокол",
    "category": "symbols",
    "sourceId": "36238",
    "source": "/assets/decor/items/36238.svg",
    "aspectRatio": 0.86953125
  },
  {
    "id": "1817589",
    "label": "Крест с растительным контуром",
    "category": "symbols",
    "sourceId": "1817589",
    "source": "/assets/decor/items/1817589.svg",
    "aspectRatio": 0.7171875
  },
  {
    "id": "2031150",
    "label": "Крест с цветочным контуром",
    "category": "symbols",
    "sourceId": "2031150",
    "source": "/assets/decor/items/2031150.svg",
    "aspectRatio": 0.7171875
  },
  {
    "id": "3151525-01",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 1",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-01.svg",
    "aspectRatio": 0.6787998032464339
  },
  {
    "id": "3151525-02",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 2",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-02.svg",
    "aspectRatio": 0.7076923076923077
  },
  {
    "id": "3151525-03",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 3",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-03.svg",
    "aspectRatio": 0.7179619145651052
  },
  {
    "id": "3151525-04",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 4",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-04.svg",
    "aspectRatio": 0.7160367722165477
  },
  {
    "id": "3151525-05",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 5",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-05.svg",
    "aspectRatio": 0.6236363636363635
  },
  {
    "id": "3151525-06",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 6",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-06.svg",
    "aspectRatio": 0.711340206185567
  },
  {
    "id": "3151525-07",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 7",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-07.svg",
    "aspectRatio": 0.711340206185567
  },
  {
    "id": "3151525-08",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 8",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-08.svg",
    "aspectRatio": 0.715463917525773
  },
  {
    "id": "3151525-09",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 9",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-09.svg",
    "aspectRatio": 0.6959183673469387
  },
  {
    "id": "3151525-10",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 10",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-10.svg",
    "aspectRatio": 0.7022900763358778
  },
  {
    "id": "3151525-11",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 11",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-11.svg",
    "aspectRatio": 0.7015840572304549
  },
  {
    "id": "3151525-12",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 12",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-12.svg",
    "aspectRatio": 0.7092488502810426
  },
  {
    "id": "3151525-13",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 13",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-13.svg",
    "aspectRatio": 0.7081632653061222
  },
  {
    "id": "3151525-14",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 14",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-14.svg",
    "aspectRatio": 0.6905940594059405
  },
  {
    "id": "3151525-15",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 15",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-15.svg",
    "aspectRatio": 0.6961904761904761
  },
  {
    "id": "3151525-16",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 16",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-16.svg",
    "aspectRatio": 0.7081632653061225
  },
  {
    "id": "3151525-17",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 17",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-17.svg",
    "aspectRatio": 0.700507614213198
  },
  {
    "id": "3151525-18",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 18",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-18.svg",
    "aspectRatio": 0.7109533468559839
  },
  {
    "id": "3151525-19",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 19",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-19.svg",
    "aspectRatio": 0.7156565656565659
  },
  {
    "id": "3151525-20",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 20",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-20.svg",
    "aspectRatio": 0.7142121524201851
  },
  {
    "id": "3151525-21",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 21",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-21.svg",
    "aspectRatio": 0.7194871794871796
  },
  {
    "id": "3151525-22",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 22",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-22.svg",
    "aspectRatio": 0.7045454545454546
  },
  {
    "id": "3151525-23",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 23",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-23.svg",
    "aspectRatio": 0.6934343434343432
  },
  {
    "id": "3151525-24",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 24",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-24.svg",
    "aspectRatio": 0.7085427135678392
  },
  {
    "id": "3151525-25",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 25",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-25.svg",
    "aspectRatio": 0.7193877551020408
  },
  {
    "id": "3151525-26",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 26",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-26.svg",
    "aspectRatio": 0.7062118126272908
  },
  {
    "id": "3151525-27",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 27",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-27.svg",
    "aspectRatio": 0.7102851323828917
  },
  {
    "id": "3151525-28",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 28",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-28.svg",
    "aspectRatio": 0.708080808080808
  },
  {
    "id": "3151525-29",
    "sourceId": "3151525",
    "label": "Пасхальное яйцо 29",
    "category": "symbols",
    "source": "/assets/decor/items/3151525-29.svg",
    "aspectRatio": 0.7121212121212122
  }
] as const;
