<?php
declare(strict_types=1);

// These public API supplements also apply to previously saved CMS pages.
function calendar_api_legal_blocks(string $slug, string $language): array {
    $texts = [
        'agb' => [
            'ru' => 'Публичный календарный API. Оператор — Volodymyr Atapin, ATAPIN.DE; контакты указаны в Impressum. API kalender.georg-kloster.ru предоставляет даты, праздники, посты и чтения для сайтов и WordPress-плагина Georg-Kloster Calendar Workshop. Обычный публичный доступ не требует регистрации или ключа и ограничен разрешёнными маршрутами, диапазоном 1900–2200 и лимитами запросов. Дополнительный доступ может требовать персонального ключа. Не обходите ограничения, не передавайте ключи третьим лицам и проверяйте полученные календарные сведения перед публикацией или печатью. Доступность и полнота данных не гарантируются; обязательная ответственность по закону сохраняется. Тексты, переводы и изображения внешних поставщиков подчиняются условиям и правам соответствующих правообладателей. Bible Desktop является отдельным источником; его документы: https://bible-desktop.com/pages/api-terms и https://bible-desktop.com/pages/api-privacy.',
            'de' => 'Öffentliche Kalender-API. Anbieter ist Volodymyr Atapin, ATAPIN.DE; Kontaktangaben stehen im Impressum. Die API kalender.georg-kloster.ru liefert Kalenderdaten, Feiertage, Fastenregeln und Lesungen für Websites und das WordPress-Plugin Georg-Kloster Calendar Workshop. Der reguläre öffentliche Zugriff benötigt weder Registrierung noch Schlüssel und ist auf erlaubte Endpunkte, die Jahre 1900–2200 und Anfragekontingente beschränkt. Erweiterter Zugriff kann einen persönlichen Schlüssel voraussetzen. Umgehen Sie keine Limits, geben Sie Schlüssel nicht weiter und prüfen Sie Kalenderangaben vor Veröffentlichung oder Druck. Verfügbarkeit und Vollständigkeit werden nicht garantiert; zwingende gesetzliche Haftung bleibt bestehen. Externe Texte, Übersetzungen und Bilder unterliegen den Rechten und Bedingungen ihrer jeweiligen Anbieter. Für Bible Desktop gelten zusätzlich https://bible-desktop.com/pages/api-terms und https://bible-desktop.com/pages/api-privacy.',
            'en' => 'Public calendar API. The operator is Volodymyr Atapin, ATAPIN.DE; contact details are in the Impressum. The kalender.georg-kloster.ru API supplies calendar dates, feasts, fasting rules and readings to websites and Georg-Kloster Calendar Workshop. Regular public use needs no registration or key and is limited to allowed endpoints, years 1900–2200 and request quotas. Extended access may require a personal key. Do not bypass limits or share keys; verify calendar information before publishing or printing it. Availability and completeness are not guaranteed; mandatory statutory liability remains unaffected. External texts, translations and images remain subject to their respective owners’ rights and terms. Bible Desktop is a separate source with terms at https://bible-desktop.com/pages/api-terms and privacy information at https://bible-desktop.com/pages/api-privacy.',
        ],
        'datenschutz' => [
            'ru' => 'Обработка запросов публичного календарного API. Ответственный — Volodymyr Atapin, ATAPIN.DE; контакт указан в Impressum. При загрузке календарного блока или переключении даты WordPress-сервер передаёт дату или период, язык, календарный профиль, параметры отображения и открытый идентификатор X-Calendar-Client: orthocal-wordpress. При настроенном расширенном доступе передаётся API-ключ. API получает IP WordPress-сервера, время, маршрут и технические HTTP-заголовки; плагин не передаёт IP посетителя, его имя, email, содержимое записей или пароль WordPress. Серверные счётчики, кэш и журналы используются для обработки запросов, безопасности и ограничения злоупотреблений (ст. 6(1)(b) и 6(1)(f) GDPR). Технические данные и резервные копии хранятся в пределах необходимости эксплуатации и применимых обязанностей; автоматический фиксированный срок удаления не обещается. Для текстов и икон календарный сервис может обращаться к Bible Desktop с датой, языком и идентификатором материала; ключ WordPress этому поставщику не передаётся. WordPress также обращается к Bible Desktop напрямую для чтений и библиотеки. Политика поставщика: https://bible-desktop.com/pages/api-privacy. Для запросов о доступе, исправлении, удалении или возражении используйте контакт оператора; права и надзорный орган указаны выше.',
            'de' => 'Verarbeitung öffentlicher Kalender-API-Anfragen. Verantwortlicher ist Volodymyr Atapin, ATAPIN.DE; Kontakt siehe Impressum. Beim Laden eines Kalenderblocks oder Wechseln des Datums übermittelt der WordPress-Server Datum oder Zeitraum, Sprache, Kalenderprofil, Anzeigeparameter und die öffentliche Kennung X-Calendar-Client: orthocal-wordpress. Bei eingerichtetem erweitertem Zugriff wird der API-Schlüssel gesendet. Der Dienst erhält die IP-Adresse des WordPress-Servers, Zeitpunkt, Endpunkt und technische HTTP-Header. Das Plugin sendet weder Besucher-IP noch Namen, E-Mail-Adressen, Beitragsinhalte oder WordPress-Passwörter. Zähler, Cache und technische Protokolle dienen der Bereitstellung, Sicherheit und Missbrauchsprävention (Art. 6 Abs. 1 lit. b und f DSGVO). Technische Daten und Sicherungskopien werden nach betrieblicher Erforderlichkeit und gesetzlichen Pflichten aufbewahrt; eine feste automatische Löschfrist wird nicht zugesagt. Für Texte und Bilder kann der Kalenderdienst Bible Desktop mit Datum, Sprache und Materialkennung abfragen; der WordPress-Schlüssel wird nicht weitergegeben. WordPress fragt Bible Desktop auch direkt für Lesungen und Bibliotheken ab. Datenschutzhinweise des Anbieters: https://bible-desktop.com/pages/api-privacy. Für Auskunft, Berichtigung, Löschung und Widerspruch kontaktieren Sie den Betreiber; Rechte und Aufsichtsbehörde sind oben beschrieben.',
            'en' => 'Public calendar API request processing. The controller is Volodymyr Atapin, ATAPIN.DE; see the Impressum for contact details. Loading a calendar block or changing its date sends the date or period, language, calendar profile, display parameters and public X-Calendar-Client: orthocal-wordpress identifier from the WordPress server. A configured key is sent for extended access. The service receives the WordPress server IP, request time, endpoint and technical HTTP headers. The plugin does not send visitor IP addresses, names, email addresses, post contents or WordPress passwords. Counters, cache and technical logs support service delivery, security and abuse prevention under GDPR Article 6(1)(b) and 6(1)(f). Technical data and backups are retained as needed for operation and statutory obligations; no fixed automatic deletion period is promised. For texts and icons, the calendar service may request Bible Desktop data using dates, languages and material identifiers; the WordPress key is not forwarded. WordPress also requests readings and libraries directly from Bible Desktop. See https://bible-desktop.com/pages/api-privacy. Contact the operator for access, correction, deletion or objections; rights and supervisory authority are described above.',
        ],
    ];
    if (!isset($texts[$slug])) return [];
    return [['type'=>'text', 'text'=>$texts[$slug][$language] ?? $texts[$slug]['en'], 'url'=>'']];
}
