<script setup lang="ts">
import {onMounted,ref} from 'vue';
import {localizedPath} from '../navigation';
import {interfaceLanguage,INTERFACE_LANGUAGE_OPTIONS} from '../i18n/interface-language';
type Plan={id:string;name:string;priceCents:number;currency:string;perMinute:number;perDay:number;perMonth:number};
const plans=ref<Plan[]>([]),contact=ref(''),wordpressUrl=ref(''),error=ref(''),loading=ref(true);
const base='https://kalender.georg-kloster.ru/api/v1/calendar/';
const example=`curl '${base}day?date=2027-05-02&lang=ru&profile=typikon-strict' \\\n  -H 'X-API-Key: YOUR_API_KEY'`;
const endpoints=[['today','Сегодня, без ключа; дата по Europe/Berlin'],['day?date=2027-05-02','Полные данные одного дня'],['month?year=2027&month=5','Все дни месяца'],['year?year=2027','Все дни года'],['pascha?year=2027','Дата Пасхи'],['upcoming?date=2027-05-01&limit=5&filter=main','Ближайшие праздники']];
onMounted(async()=>{try{const r=await fetch('/api/v1/calendar-access/plans',{credentials:'omit'});if(!r.ok)throw new Error();const data=await r.json();plans.value=data.plans;contact.value=data.settings?.contactEmail||'';if(typeof data.settings?.wordpressUrl==='string'&&data.settings.wordpressUrl.startsWith('https://'))wordpressUrl.value=data.settings.wordpressUrl;}catch{error.value='Не удалось загрузить тарифы. Документация и скачивание доступны; повторите загрузку страницы позже.';}finally{loading.value=false;}});
</script>
<template><main class="api-docs">
  <header><a :href="localizedPath('/')">← На главную</a><select v-model="interfaceLanguage" aria-label="Язык"><option v-for="language in INTERFACE_LANGUAGE_OPTIONS" :key="language.id" :value="language.id">{{language.nativeLabel}}</option></select></header>
  <p class="eyebrow">ДЛЯ САЙТОВ, ПРИЛОЖЕНИЙ И WORDPRESS</p><h1>API календаря</h1>
  <p class="lead">Православный календарь для вашего сайта. Праздники, памяти святых, посты, чтения и знаки Типикона — из той же базы, что и в Календарной мастерской.</p>
  <nav><a href="#connection">Подключение</a><a href="#data">Данные и запросы</a><a v-if="plans.length" href="#plans">Тарифы</a><a href="#wordpress">WordPress-плагин</a></nav>
  <section id="connection"><h2>Подключение</h2><p>Ответы в JSON, API v1, годы 1900–2200. Даты запроса — по новому стилю (григорианские), старый стиль возвращается отдельно.</p><pre data-no-translate>{{base}}</pre>
  <ol><li>Получите индивидуальный ключ у администратора. Ключ создаётся для конкретного клиента и тарифа.</li><li>Отправляйте его в заголовке <code data-no-translate>X-API-Key</code> или <code data-no-translate>Authorization: Bearer YOUR_API_KEY</code>.</li><li>Храните ключ на сервере. Не вставляйте его в публичный JavaScript, URL или репозиторий.</li></ol>
  <pre data-no-translate>{{example}}</pre><p>Корневой запрос с метаданными и <code>today</code> доступны без ключа. Остальные запросы требуют ключа.</p>
  <a href="/calendar-api-test" target="_blank" rel="noopener">Открыть тестовую HTML-страницу ↗</a></section>
  <section id="data"><h2>Данные и запросы</h2><div class="table-wrap"><table><thead><tr><th>GET-запрос</th><th>Результат</th></tr></thead><tbody><tr v-for="[path,label] in endpoints" :key="path"><td><code data-no-translate>{{path}}</code></td><td>{{label}}</td></tr></tbody></table></div>
  <p>Параметр <code>lang</code>: <code>ru, cu, de, uk, pl</code>. Параметр <code>profile</code>: <code>typikon-strict</code> (строгий устав) или <code>parish</code> (приходской профиль). По умолчанию: русский и строгий профиль.</p>
  <p>Месяц и год принимают <code>view=summary</code> для лёгкого представления. Для ближайших событий: <code>limit=1…10</code>, <code>filter=main|twelve|great|memorial|all</code>.</p>
  <p>Ответ дня: <code>{metadata, day}</code>. В <code>day</code> находятся гражданская и юлианская даты, день недели, Пасха и расстояние от неё, правило поста, все события движка, названия памятей икон, ссылки на чтения и знаки Типикона. В событиях есть полные и краткие названия, тип и сведения об источнике. Русский <code>sourceTitle</code> — исходник, не потерянный перевод.</p>
  <p>Поле day.icons содержит доступные изображения икон из каталога; новые иконки подключаются без изменения формата API. Жития и местное расписание служб не подключены. Структурированные чтения содержат библейские ссылки, а не сами стихи. Личные календари и фотографии не выдаются.</p>
  <h3>Ошибки и кэш</h3><p><code>400</code> — неверные параметры; <code>401</code> — неверный ключ; <code>403</code> — доступ отключён или истёк; <code>429</code> — лимит запросов; <code>503</code> — сервис временно недоступен. При ограничении соблюдайте <code>Retry-After</code>, не повторяйте запрос непрерывно.</p>
  <p>Успешный календарный ответ разрешено кэшировать в приложении до 300 секунд по заголовку <code>X-Calendar-Application-Cache-TTL</code>. Ключ кэша включает дату, язык, профиль и остальные параметры. Ошибки не сохраняются как данные. Краткий срок позволяет применять изменения базы и отключение доступа; мгновенный отзыв уже закэшированного ответа невозможен.</p>
  <h3>Богослужебный справочник и служба дня</h3><p><code>/api/v1/calendar-texts/</code> — 98 церковнославянских текстов: тропари, кондаки, молитвы и величания. Используется тот же API-ключ. Фильтры: <code>id, type, scope, tone, weekday, language</code>. Справочник не назначает текст дню сам.</p><p><code>/api/v1/calendar/service?date=2027-06-06&amp;office=sixth-hour&amp;expansion=full</code> возвращает суточный, седмичный, годовой и подвижный круги, календарные вставки и полный текст общеупотребительных сокращений. Библейские места в этот маршрут не входят.</p>
  <a href="/downloads/calendar-api-guide.md" download>Скачать подробную документацию (Markdown)</a></section>
  <section v-if="plans.length" id="plans"><h2>Тарифы и доступ</h2><p v-if="loading" role="status">Загрузка тарифов…</p><p v-if="error" role="alert">{{error}}</p><div class="cards"><article v-for="plan in plans" :key="plan.id"><h3 data-no-translate>{{plan.name}}</h3><p class="price">{{new Intl.NumberFormat('ru',{style:'currency',currency:plan.currency}).format(plan.priceCents/100)}} / месяц</p><p>{{plan.perMinute}} запросов в минуту<br>{{plan.perDay}} в день<br>{{plan.perMonth}} в месяц</p></article></div><p>Лимиты считаются по UTC. Стоимость и условия назначает администратор. Платный доступ согласуется вручную, автоматических списаний нет.</p><a v-if="contact" :href="'mailto:'+contact">Запросить API-ключ</a><p v-else>Для получения ключа свяжитесь с владельцем Календарной мастерской.</p></section>
  <section id="wordpress"><h2>Плагин для WordPress</h2><p>19 независимых блоков Gutenberg и шорткодов: сегодня, выбранный день, месяц, год, ближайшие праздники и чтения. Можно установить только один нужный блок. Три оформления, компактный режим, старый стиль и пять языков календарных текстов.</p>
  <a class="download" href="/downloads/orthocal-1.3.28.zip" download>Скачать WordPress-плагин · 1.3.28</a><p>Требования: WordPress 6.3+, PHP 8.0+. Установите ZIP через «Плагины → Добавить → Загрузить плагин», затем укажите ключ в «Настройки → Православный календарь».</p>
  <p>Шесть вкладок настроек, конструктор шорткодов с предпросмотром и встроенная помощь. День и чтения открываются внутри блока или во всплывающем окне. Картинки поста и шрифт хранятся на вашем WordPress с проверкой обновлений. Место для икон подготовлено; акафисты относятся к отдельной библиотеке BibleDesktop.</p>
  <pre data-no-translate>[orthocal_today]
[orthocal_month]
[orthocal_day date="2027-05-02" lang="uk"]</pre><p>Плагин получает календарные данные только из нашего API: XML и расчётов дат внутри нет. Запросы кэшируются на сервере WordPress; ключ посетителям не раскрывается. Для текста библейских чтений отдельно используется BibleDesktop; календарный ключ ему не передаётся. Интерфейс плагина пока русский.</p><p>После обновления настроек кэш сбрасывается. При использовании CDN или полностраничного кэша исключите из него страницы с календарём, особенно блоки в шаблонах и виджетах.</p></section>
  <p v-if="wordpressUrl"><a :href="wordpressUrl" target="_blank" rel="noopener noreferrer">Дополнительная страница WordPress-плагина ↗</a></p>
</main></template>
<style scoped>
.api-docs{max-width:1120px;margin:auto;padding:30px 24px 70px;color:#f4ead1;line-height:1.65;box-sizing:border-box}header,nav{display:flex;gap:22px;flex-wrap:wrap;align-items:center}header{justify-content:space-between}a{color:#e4c779}h1{font:clamp(36px,6vw,64px) Georgia,serif;margin:15px 0}h2{font:32px Georgia,serif}h3{font-size:21px}.eyebrow{font-size:12px;letter-spacing:.13em;color:#cfaf58;margin-top:60px}.lead{font-size:21px;max-width:850px}section{margin-top:45px;padding:26px;border:1px solid #425449;border-radius:12px;background:#19271f;scroll-margin-top:20px}pre{padding:18px;background:#101b16;border-radius:8px;overflow:auto;font-size:14px}code{overflow-wrap:anywhere}nav{padding:20px 0}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:14px;border-bottom:1px solid #425449}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,240px),1fr));gap:20px}article{padding:20px;border:1px solid #75683f;border-radius:8px}.price{font-size:25px}.download{display:inline-block;background:#d6b351;color:#17241d;padding:13px 22px;border-radius:6px;font-weight:bold;text-decoration:none}select{max-width:180px}@media(max-width:600px){.api-docs{padding:20px 14px}section{padding:18px}li{margin:10px 0}}
</style>
