<script setup lang="ts">
import {onMounted,ref} from 'vue';
import {localizedPath} from '../navigation';
import {interfaceLanguage,INTERFACE_LANGUAGE_OPTIONS} from '../i18n/interface-language';
type Plan={id:string;name:string;priceCents:number;currency:string;perMinute:number;perDay:number;perMonth:number};
const plans=ref<Plan[]>([]),contact=ref(''),wordpressUrl=ref(''),error=ref(''),loading=ref(true);
const wordpressPluginDownload='https://github.com/VAtapin/wp_orthodox_calendar/releases/latest/download/orthocal.zip';
const translatorPluginDownload='https://github.com/VAtapin/wp_cu_translator/releases/latest/download/church-slavonic-translator.zip';
const base='https://kalender.georg-kloster.ru/api/v1/calendar/';
const example=`curl '${base}day?date=2027-05-02&lang=ru&profile=typikon-strict' \\\n  -H 'X-API-Key: YOUR_API_KEY'`;
const wordpressExample=`curl '${base}day?date=2027-05-02&lang=ru&profile=typikon-strict' -H 'X-Calendar-Client: orthocal-wordpress'`;
const endpoints=[['today','Сегодня, без ключа; дата по Europe/Berlin'],['day?date=2027-05-02','Полные данные одного дня'],['month?year=2027&month=5','Все дни месяца'],['year?year=2027','Все дни года'],['pascha?year=2027','Дата Пасхи'],['upcoming?date=2027-05-01&limit=5&filter=main','Ближайшие праздники']];
onMounted(async()=>{try{const r=await fetch('/api/v1/calendar-access/plans',{credentials:'omit'});if(!r.ok)throw new Error();const data=await r.json();plans.value=data.plans;contact.value=data.settings?.contactEmail||'';if(typeof data.settings?.wordpressUrl==='string'&&data.settings.wordpressUrl.startsWith('https://'))wordpressUrl.value=data.settings.wordpressUrl;}catch{error.value='Не удалось загрузить тарифы. Документация и скачивание доступны; повторите загрузку страницы позже.';}finally{loading.value=false;}});
</script>
<template><main class="api-docs">
  <header><a :href="localizedPath('/')">← На главную</a><select v-model="interfaceLanguage" aria-label="Язык"><option v-for="language in INTERFACE_LANGUAGE_OPTIONS" :key="language.id" :value="language.id">{{language.nativeLabel}}</option></select></header>
  <p class="eyebrow">ДЛЯ САЙТОВ, ПРИЛОЖЕНИЙ И WORDPRESS</p><h1>API календаря</h1>
  <p class="lead">Православный календарь для вашего сайта. Праздники, памяти святых, посты, чтения и знаки Типикона — из той же базы, что и в Календарной мастерской.</p>
  <nav><a href="#connection">Подключение</a><a href="#data">Данные и запросы</a><a v-if="plans.length" href="#plans">Тарифы</a><a href="#wordpress">Плагин календаря</a><a href="#translator-plugin">Плагин-переводчик</a></nav>
  <section id="connection"><h2>Подключение</h2><p>Ответы в JSON, API v1, годы 1900–2200. Даты запроса — по новому стилю (григорианские), старый стиль возвращается отдельно.</p><pre data-no-translate>{{base}}</pre>
  <p>Для расширенной серверной интеграции получите индивидуальный ключ у администратора. Он создаётся для конкретного клиента и тарифа; отправляйте его в <code data-no-translate>X-API-Key</code> или <code data-no-translate>Authorization: Bearer YOUR_API_KEY</code> и храните только на сервере, не в JavaScript, URL или репозитории.</p>
  <pre data-no-translate>{{example}}</pre><p>Корневой запрос с метаданными и <code>today</code> доступны без ключа. Официальный WordPress-плагин работает без регистрации и ключа: для <code>day</code>, <code>month</code>, <code>year</code>, <code>pascha</code> и <code>upcoming</code> он передаёт открытый идентификатор клиента.</p>
  <pre data-no-translate>{{wordpressExample}}</pre><p><code data-no-translate>X-Calendar-Client: orthocal-wordpress</code> не является секретом и не открывает расширенный доступ. Для него действуют allowlist маршрутов и параметров, диапазон 1900–2200, серверный кэш и лимиты 90 запросов в минуту и 5000 в сутки на IP сервера WordPress.</p>
  <a href="/calendar-api-test" target="_blank" rel="noopener">Открыть тестовую HTML-страницу ↗</a></section>
  <section id="data"><h2>Данные и запросы</h2><div class="table-wrap"><table><thead><tr><th>GET-запрос</th><th>Результат</th></tr></thead><tbody><tr v-for="[path,label] in endpoints" :key="path"><td><code data-no-translate>{{path}}</code></td><td>{{label}}</td></tr></tbody></table></div>
  <p>Параметр <code>lang</code>: <code>ru, cu, de, uk, pl</code>. Параметр <code>profile</code>: <code>typikon-strict</code> (строгий устав) или <code>parish</code> (приходской профиль). По умолчанию: русский и строгий профиль.</p>
  <p>Месяц и год принимают <code>view=summary</code> для лёгкого представления. Для ближайших событий: <code>limit=1…10</code>, <code>filter=main|twelve|great|memorial|all</code>.</p>
  <p>Ответ дня: <code>{metadata, day}</code>. В <code>day</code> находятся гражданская и юлианская даты, день недели, Пасха и расстояние от неё, правило поста, все события движка, названия памятей икон, ссылки на чтения и знаки Типикона. В событиях есть полные и краткие названия, тип и сведения об источнике. Русский <code>sourceTitle</code> — исходник, не потерянный перевод.</p>
  <p>Поле day.icons содержит доступные изображения икон из каталога; новые иконки подключаются без изменения формата API. Жития и местное расписание служб не подключены. Структурированные чтения содержат библейские ссылки, а не сами стихи. Личные календари и фотографии не выдаются.</p>
  <h3>Ошибки и кэш</h3><p><code>400</code> — неверные параметры; <code>401</code> — нужен действующий ключ или разрешённый идентификатор клиента; <code>403</code> — доступ по ключу отключён или истёк; <code>429</code> — лимит запросов; <code>503</code> — сервис временно недоступен. При ограничении соблюдайте <code>Retry-After</code>, не повторяйте запрос непрерывно.</p>
  <p>Успешный календарный ответ разрешено кэшировать в приложении до 300 секунд по заголовку <code>X-Calendar-Application-Cache-TTL</code>. Ключ кэша включает дату, язык, профиль и остальные параметры. Ошибки не сохраняются как данные. Краткий срок позволяет применять изменения базы и отключение доступа; мгновенный отзыв уже закэшированного ответа невозможен.</p>
  <h3>Богослужебный справочник и служба дня</h3><p><code>/api/v1/calendar-texts/</code> — библиотека текстов Bible Desktop: тропари, кондаки, молитвы и величания. Используется тот же API-ключ. Фильтры: <code>id, type, scope, tone, weekday, language</code>. Справочник не назначает текст дню сам.</p><p><code>/api/v1/calendar/service?date=2027-06-06&amp;office=sixth-hour&amp;expansion=full</code> возвращает суточный, седмичный, годовой и подвижный круги, календарные вставки и полный текст общеупотребительных сокращений. Библейские места в этот маршрут не входят.</p>
  <a href="/downloads/calendar-api-guide.md" download>Скачать подробную документацию (Markdown)</a></section>
  <section v-if="plans.length" id="plans"><h2>Тарифы и доступ</h2><p v-if="loading" role="status">Загрузка тарифов…</p><p v-if="error" role="alert">{{error}}</p><div class="cards"><article v-for="plan in plans" :key="plan.id"><h3 data-no-translate>{{plan.name}}</h3><p class="price">{{new Intl.NumberFormat('ru',{style:'currency',currency:plan.currency}).format(plan.priceCents/100)}} / месяц</p><p>{{plan.perMinute}} запросов в минуту<br>{{plan.perDay}} в день<br>{{plan.perMonth}} в месяц</p></article></div><p>Лимиты считаются по UTC. Стоимость и условия назначает администратор. Платный доступ согласуется вручную, автоматических списаний нет.</p><a v-if="contact" :href="'mailto:'+contact">Запросить API-ключ</a><p v-else>Для получения ключа свяжитесь с владельцем Календарной мастерской.</p></section>
  <section id="wordpress"><h2>Плагин для WordPress</h2><p>22 независимых видов календаря: сегодняшний и выбранный день, месяц, год, праздники, пост, памяти, чтения, Пасха, посты, дата по двум стилям, богослужебные тексты, Часослов, каноны и акафисты. Каждый доступен и как отдельный блок Gutenberg, и как обычный шорткод — можно разместить на странице только нужный элемент.</p>
  <p>В Часослове и молитвенной библиотеке язык текста выбирается отдельно от языка календаря. Если язык не задан, плагин открывает редакцию с наибольшим количеством материалов. Доступны полные произведения Bible Desktop и сохранённые русские переводы. Церковнославянские издания традиционным и гражданским шрифтом различаются; отсутствующий перевод не подменяется другим языком.</p>
  <a class="download" :href="wordpressPluginDownload">Скачать последнюю версию WordPress-плагина</a><p>Требования: WordPress 6.3+, PHP 8.0+. Установите ZIP через «Плагины → Добавить → Загрузить плагин» и активируйте: календарь работает сразу, без регистрации и API-ключа. В меню «Православный календарь» можно добавить необязательный ключ для расширенного или авторизованного доступа.</p>
  <p>В меню плагина есть подключение, генератор и помощь. Генератор собирает шорткод из выбранных параметров, сразу показывает живой предпросмотр и копирует готовую строку для вставки. Настраиваются оформление, компактный режим, старый стиль, язык календаря, профиль поста, состав карточки, изображения и иконы, переходы, чтения и раздел Часослова. Карточка дня открывается внутри блока, во всплывающем окне, на отдельной странице или в новом окне.</p>
  <p>Знаки поста, Типикона, календарные изображения и церковнославянский шрифт сохраняются в WordPress и проверяются на обновления. Библейские чтения получают текст из BibleDesktop; календарный ключ туда не передаётся. Справочник богослужебных текстов включает тропари, кондаки, молитвы, величания и Часослов.</p>
  <pre data-no-translate>[orthocal_today]
[orthocal_month]
[orthocal_day date="2027-05-02" lang="uk"]</pre><p>Плагин получает календарные данные только из нашего API: XML и расчётов дат внутри нет. Запросы кэшируются на сервере WordPress. Открытый идентификатор WordPress-плагина не является ключом; если задан дополнительный ключ, он не раскрывается посетителям. Для текста библейских чтений отдельно используется BibleDesktop; календарный ключ ему не передаётся. Название и краткое описание плагина в списке WordPress локализованы для русского, немецкого и английского языка интерфейса.</p><p>После обновления настроек кэш сбрасывается. При использовании CDN или полностраничного кэша исключите из него страницы с календарём, особенно блоки в шаблонах и виджетах.</p></section>
  <section id="translator-plugin"><h2>Церковнославянский переводчик для WordPress</h2>
  <p><strong>Church Slavonic Translator</strong> добавляет на сайт форму перевода русского и немецкого текста на традиционный церковнославянский язык через шорткод <code data-no-translate>[wp_cu_translator]</code>. Интерфейс, настройки и описание плагина доступны на русском, немецком и английском языках.</p>
  <p>Библейские ссылки и уверенно распознанные цитаты возвращаются из проверенного корпуса Bible Desktop, а повторные переводы — из серверного кэша. Для остальных текстов используется ИИ с полной церковнославянской Unicode-орфографией, ударениями, титлами и придыханиями. Результат можно скопировать обычным текстом или с форматированием для Word; рядом доступен шрифт Monomakh Unicode.</p>
  <p>Бесплатный режим работает сразу после активации и не требует регистрации или API-ключа. Необязательный ключ Bible Desktop включает повышенные лимиты и хранится только на сервере WordPress.</p>
  <div class="plugin-actions"><a class="download" :href="translatorPluginDownload">Скачать последнюю версию WordPress-плагина</a></div>
  <p>Требования: WordPress 6.3+, PHP 8.0+. Установите ZIP через «Плагины → Добавить → Загрузить плагин» и активируйте его. Релиз публикуется отдельно от календарного плагина; автоматическая публикация в каталоге WordPress.org пока не включена.</p></section>
  <p v-if="wordpressUrl"><a :href="wordpressUrl" target="_blank" rel="noopener noreferrer">Дополнительная страница WordPress-плагина ↗</a></p>
</main></template>
<style scoped>
.api-docs{max-width:1120px;margin:auto;padding:30px 24px 70px;color:#f4ead1;line-height:1.65;box-sizing:border-box}header,nav,.plugin-actions{display:flex;gap:22px;flex-wrap:wrap;align-items:center}header{justify-content:space-between}a{color:#e4c779}h1{font:clamp(36px,6vw,64px) Georgia,serif;margin:15px 0}h2{font:32px Georgia,serif}h3{font-size:21px}.eyebrow{font-size:12px;letter-spacing:.13em;color:#cfaf58;margin-top:60px}.lead{font-size:21px;max-width:850px}section{margin-top:45px;padding:26px;border:1px solid #425449;border-radius:12px;background:#19271f;scroll-margin-top:20px}pre{padding:18px;background:#101b16;border-radius:8px;overflow:auto;font-size:14px}code{overflow-wrap:anywhere}nav{padding:20px 0}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:14px;border-bottom:1px solid #425449}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,240px),1fr));gap:20px}article{padding:20px;border:1px solid #75683f;border-radius:8px}.price{font-size:25px}.download{display:inline-block;background:#d6b351;color:#17241d;padding:13px 22px;border-radius:6px;font-weight:bold;text-decoration:none}.plugin-actions{margin:20px 0}select{max-width:180px}@media(max-width:600px){.api-docs{padding:20px 14px}section{padding:18px}li{margin:10px 0}}
</style>
