<script setup lang="ts">
import {onMounted} from 'vue';
import {localizedPath} from '../navigation';
import {interfaceLanguage,INTERFACE_LANGUAGE_OPTIONS} from '../i18n/interface-language';
const wordpressPluginDownload=`/downloads/orthocal-${__WORDPRESS_PLUGIN_VERSION__}.zip`;
const translatorPluginVersion='1.0.5';
const translatorPluginDownload=`/downloads/georg-kloster-slavonic-translator-${translatorPluginVersion}.zip`;
const prayerPluginDownload='/downloads/kloster-prayer-1.2.5.zip';
const calendarVersion=__WORDPRESS_PLUGIN_VERSION__;
function openPlugin(id:string){const panel=document.getElementById(id);if(panel instanceof HTMLDetailsElement)panel.open=true;}
onMounted(()=>{const id=window.location.hash.slice(1);if(['wordpress','prayer-plugin','translator-plugin'].includes(id)){openPlugin(id);document.getElementById(id)?.scrollIntoView();}});
const base=__PUBLIC_API_URL__+'/api/v1/calendar/';
const wordpressExample=`curl '${base}day?date=2027-05-02&lang=ru&profile=typikon-strict' -H 'X-Calendar-Client: orthocal-wordpress'`;
const endpoints=[['today','Сегодня, без ключа; дата по Europe/Berlin'],['day?date=2027-05-02','Полные данные одного дня'],['month?year=2027&month=5','Все дни месяца'],['year?year=2027','Все дни года'],['pascha?year=2027','Дата Пасхи'],['upcoming?date=2027-05-01&limit=5&filter=main','Ближайшие праздники']];
</script>
<template><main class="api-docs">
  <header><a :href="localizedPath('/')">← На главную</a><select v-model="interfaceLanguage" aria-label="Язык"><option v-for="language in INTERFACE_LANGUAGE_OPTIONS" :key="language.id" :value="language.id">{{language.nativeLabel}}</option></select></header>
  <p class="eyebrow">ДЛЯ САЙТОВ, ПРИЛОЖЕНИЙ И WORDPRESS</p><h1>API календаря</h1>
  <p class="lead">Православный календарь для вашего сайта. Праздники, памяти святых, посты, чтения и знаки Типикона — из API Bible Desktop.</p>
  <nav><a href="#plugins">Плагины WordPress</a><a href="#connection">Подключение API</a><a href="#data">Документация</a></nav>
  <section id="plugins" class="plugin-catalog" aria-labelledby="plugins-title">
    <div class="catalog-heading"><h2 id="plugins-title">Плагины для WordPress</h2><span>3 плагина · atapin.de</span></div>
    <p class="catalog-intro">Выберите нужный плагин. Скачайте ZIP и установите его через раздел «Плагины» в WordPress.</p>
    <table class="plugin-table"><caption class="visually-hidden">Плагины, возможности, версии и скачивание</caption><thead><tr><th scope="col">Плагин</th><th scope="col">Возможности</th><th scope="col">Версия</th><th scope="col">Установка</th></tr></thead><tbody>
      <tr><th scope="row"><span class="plugin-title">Календарь</span><small data-no-translate>Georg-Kloster Calendar Workshop</small></th><td>Календарь, чтения и богослужебные тексты.<small>WordPress 6.3+ · PHP 8.0+</small></td><td><span class="version" data-no-translate>{{calendarVersion}}</span></td><td><a class="download" :href="wordpressPluginDownload" download aria-label="Скачать ZIP календаря">Скачать ZIP</a><a class="plugin-more" href="#wordpress" @click="openPlugin('wordpress')" aria-label="Подробнее о календаре">Подробнее ↓</a></td></tr>
      <tr><th scope="row"><span class="plugin-title">Записки и пожертвования</span><small data-no-translate>kloster-prayer</small></th><td>Требы, Stripe / PayPal, печать PDF и архив.<small>WordPress 7.1+ · PHP 8.4+</small></td><td><span class="version" data-no-translate>1.2.5</span></td><td><a class="download" :href="prayerPluginDownload" download aria-label="Скачать ZIP молитвенных записок">Скачать ZIP</a><a class="plugin-more" href="#prayer-plugin" @click="openPlugin('prayer-plugin')" aria-label="Подробнее о молитвенных записках">Подробнее ↓</a></td></tr>
      <tr><th scope="row"><span class="plugin-title">Церковнославянский переводчик</span><small data-no-translate>Georg-Kloster Slavonic Translator</small></th><td>Перевод с русского и немецкого, копирование в Word.<small>WordPress 6.3+ · PHP 8.0+</small></td><td><span class="version">{{translatorPluginVersion}}</span></td><td><a class="download" :href="translatorPluginDownload" aria-label="Скачать ZIP переводчика">Скачать ZIP</a><a class="plugin-more" href="#translator-plugin" @click="openPlugin('translator-plugin')" aria-label="Подробнее о переводчике">Подробнее ↓</a></td></tr>
    </tbody></table>
    <p class="catalog-note">Перед обновлением сделайте резервную копию сайта. Плагины устанавливаются отдельно друг от друга.</p>
  </section>
  <section id="connection"><h2>Подключение к Bible Desktop</h2><p>Единственный источник календарных событий, постов, чтений, службы дня, текстов и икон — API Bible Desktop. Календарная мастерская предоставляет редактор и скачивание плагинов.</p><pre data-no-translate>{{base}}</pre><p>Обычные календарные запросы доступны без ключа с ограничением 30 запросов в минуту. Ключи старого API Kalendar больше не используются.</p><pre data-no-translate>{{wordpressExample}}</pre></section>
  <section id="data"><h2>Документация API Bible Desktop</h2><p>Годы 1900–2200, гражданские даты; старый стиль возвращается отдельно. Язык календаря и редакция богослужебного текста выбираются независимо.</p><div class="table-wrap"><table><thead><tr><th>Маршрут</th><th>Ответ</th></tr></thead><tbody><tr v-for="[path,title] in endpoints" :key="path"><td><a :href="base+path"><code data-no-translate>{{path}}</code></a></td><td>{{title}}</td></tr></tbody></table></div><p>Служба дня: <code>/api/v1/calendar/service</code>. Библиотека текстов: <code>/api/liturgical/calendar-texts</code>; полный каталог икон: <code>/api/calendar/icons</code>. Все маршруты находятся на Bible Desktop.</p><a href="/downloads/calendar-api-guide.md" download>Скачать подробную документацию (Markdown)</a></section>
  <details class="plugin-details" id="wordpress"><summary>Календарь — установка и возможности</summary><div class="plugin-detail-body"><h2>Плагин для WordPress</h2><p>22 независимых видов календаря: сегодняшний и выбранный день, месяц, год, праздники, пост, памяти, чтения, Пасха, посты, дата по двум стилям, богослужебные тексты, Часослов, каноны и акафисты. Каждый доступен и как отдельный блок Gutenberg, и как обычный шорткод — можно разместить на странице только нужный элемент.</p>
  <p>В Часослове и молитвенной библиотеке язык текста выбирается отдельно от языка календаря. Если язык не задан, плагин открывает редакцию с наибольшим количеством материалов. Доступны полные произведения Bible Desktop и сохранённые русские переводы. Церковнославянские издания традиционным и гражданским шрифтом различаются; отсутствующий перевод не подменяется другим языком.</p>
  <a class="download" :href="wordpressPluginDownload">Скачать ZIP версии {{calendarVersion}}</a><p>Требования: WordPress 6.3+, PHP 8.0+. Установите ZIP через «Плагины → Добавить → Загрузить плагин» и активируйте: календарь работает сразу, без регистрации и API-ключа. В меню «Georg-Kloster Calendar Workshop» задаётся единый адрес API Bible Desktop.</p>
  <p>В меню плагина есть подключение, генератор и помощь. Генератор собирает шорткод из выбранных параметров, сразу показывает живой предпросмотр и копирует готовую строку для вставки. Настраиваются оформление, компактный режим, старый стиль, язык календаря, профиль поста, состав карточки, изображения и иконы, переходы, чтения и раздел Часослова. Карточка дня открывается внутри блока, во всплывающем окне, на отдельной странице или в новом окне.</p>
  <p>Знаки поста, Типикона, календарные изображения и церковнославянский шрифт сохраняются в WordPress и проверяются на обновления. Библейские чтения получают текст из BibleDesktop; календарный ключ туда не передаётся. Справочник богослужебных текстов включает тропари, кондаки, молитвы, величания и Часослов.</p>
  <pre data-no-translate>[orthocal_today]
[orthocal_month]
[orthocal_day date="2027-05-02" lang="uk"]</pre><p>Плагин получает календарные данные только из нашего API: XML и расчётов дат внутри нет. Запросы кэшируются на сервере WordPress. Открытый идентификатор WordPress-плагина не является ключом; если задан дополнительный ключ, он не раскрывается посетителям. Для текста библейских чтений отдельно используется BibleDesktop; календарный ключ ему не передаётся. Название и краткое описание плагина в списке WordPress локализованы для русского, немецкого и английского языка интерфейса.</p><p>После обновления настроек кэш сбрасывается. При использовании CDN или полностраничного кэша исключите из него страницы с календарём, особенно блоки в шаблонах и виджетах.</p></div></details>
  <details class="plugin-details" id="prayer-plugin"><summary>Записки и пожертвования — установка</summary><div class="plugin-detail-body"><h2>Православные молитвенные записки и пожертвования</h2>
  <p>Плагин автора atapin.de для приходов, храмов и монастырей: формы подачи имён, Stripe и PayPal, письма, отчёты и печать записок в PDF на трёх бланках одного листа.</p>
  <p>Версия 1.2.5: отдельный email получателя уведомлений о новых оплаченных записках задаётся в настройках. Письма жертвователю сохраняются; ошибки уведомлений повторяются через планировщик WordPress. Старые заказы автоматически не рассылаются.</p>
  <div class="plugin-actions"><a class="download" :href="prayerPluginDownload" download>Скачать плагин записок 1.2.5</a></div>
  <p>Требования: WordPress 7.1+, PHP 8.4+. Перед обновлением сохраните резервную копию сайта и базы. Установите ZIP через «Плагины → Добавить → Загрузить плагин». Настройте используемый платёжный сервис и его webhook; неиспользуемый сервис можно отключить. Отдельный ключ календарного API не требуется.</p>
  <pre data-no-translate>[kloster_form id="2"]</pre>
  <p>Существующие шорткоды сохраняются. Домен API настраивается в плагине; при переезде адреса webhook в платёжных кабинетах обновляются отдельно.</p>
  </div></details>
  <details class="plugin-details" id="translator-plugin"><summary>Переводчик — установка и возможности</summary><div class="plugin-detail-body"><h2>Церковнославянский переводчик для WordPress</h2>
  <p><strong data-no-translate>Georg-Kloster Slavonic Translator</strong> добавляет на сайт форму перевода русского и немецкого текста на традиционный церковнославянский язык через шорткод <code data-no-translate>[wp_cu_translator]</code>. Интерфейс, настройки и описание плагина доступны на русском, немецком и английском языках.</p>
  <p>Библейские ссылки и уверенно распознанные цитаты возвращаются из проверенного корпуса Bible Desktop, а повторные переводы — из серверного кэша. Для остальных текстов используется ИИ с полной церковнославянской Unicode-орфографией, ударениями, титлами и придыханиями. Результат можно скопировать обычным текстом или с форматированием для Word; рядом доступен шрифт Monomakh Unicode.</p>
  <p>Бесплатный режим работает сразу после активации и не требует регистрации или API-ключа. Необязательный ключ Bible Desktop включает повышенные лимиты и хранится только на сервере WordPress.</p>
  <div class="plugin-actions"><a class="download" :href="translatorPluginDownload">Скачать ZIP версии {{translatorPluginVersion}}</a></div>
  <p>Требования: WordPress 6.3+, PHP 8.0+. Установите ZIP через «Плагины → Добавить → Загрузить плагин» и активируйте его. Перед переходом с предыдущего имени деактивируйте старую копию плагина, но не удаляйте её через WordPress: шорткод и настройки сохраняются. Публикация в каталоге WordPress.org выполняется отдельно.</p></div></details>
</main></template>
<style scoped>
.api-docs{max-width:1120px;margin:auto;padding:30px 24px 70px;color:#f4ead1;line-height:1.65;box-sizing:border-box}header,nav,.plugin-actions{display:flex;gap:22px;flex-wrap:wrap;align-items:center}header{justify-content:space-between}a{color:#e4c779}h1{font:clamp(36px,6vw,64px) Georgia,serif;margin:15px 0}h2{font:32px Georgia,serif}h3{font-size:21px}.eyebrow{font-size:12px;letter-spacing:.13em;color:#cfaf58;margin-top:60px}.lead{font-size:21px;max-width:850px}section{margin-top:45px;padding:26px;border:1px solid #425449;border-radius:12px;background:#19271f;scroll-margin-top:20px}pre{padding:18px;background:#101b16;border-radius:8px;overflow:auto;font-size:14px}code{overflow-wrap:anywhere}nav{padding:20px 0}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:14px;border-bottom:1px solid #425449}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,240px),1fr));gap:20px}article{padding:20px;border:1px solid #75683f;border-radius:8px}.price{font-size:25px}.download{display:inline-block;background:#d6b351;color:#17241d;padding:13px 22px;border-radius:6px;font-weight:bold;text-decoration:none}.plugin-actions{margin:20px 0}select{max-width:180px}@media(max-width:600px){.api-docs{padding:20px 14px}section{padding:18px}li{margin:10px 0}}
</style>
<style scoped>
.plugin-catalog{margin-top:12px;padding:22px}.catalog-heading{display:flex;align-items:baseline;justify-content:space-between;gap:12px;flex-wrap:wrap}.catalog-heading h2{margin:0;font-size:28px}.catalog-heading span,.catalog-note{font-size:12px;color:#c5cdbf}.catalog-intro{font-size:14px;margin:10px 0 18px;color:#d2d8ca}.plugin-table{font-size:14px;line-height:1.5}.plugin-table th,.plugin-table td{padding:16px 12px;vertical-align:middle}.plugin-table thead{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:#b5c5b8;background:#142219}.plugin-table tbody th{width:31%;font-weight:normal}.plugin-table tbody tr:last-child>*{border-bottom:0}.plugin-title{font-weight:650;color:#f4ead1}.plugin-table small{display:block;margin-top:5px;font-size:11px;color:#b5c5b8}.plugin-table .version{white-space:nowrap;font-size:12px;color:#e4c779}.plugin-table .download{padding:9px 14px;font-size:12px;white-space:nowrap}.plugin-more{display:block;margin-top:7px;font-size:12px;text-decoration:none}.plugin-table a:hover{text-decoration:underline}.plugin-table tr:hover{background:#ffffff04}.catalog-note{margin:15px 0 0}.plugin-details{margin-top:14px;border:1px solid #425449;border-radius:10px;background:#19271f;scroll-margin-top:20px}.plugin-details summary{padding:16px 22px;cursor:pointer;color:#e4c779;font-weight:600;font-size:15px}.plugin-detail-body{padding:0 24px 22px}.plugin-detail-body h2{font-size:25px;margin-top:10px}.plugin-details[open] summary{border-bottom:1px solid #425449;margin-bottom:18px}.plugin-table a:focus-visible,summary:focus-visible{outline:2px solid #e4c779;outline-offset:4px}.visually-hidden{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap;border:0}
@media(max-width:700px){.plugin-catalog{padding:18px}.plugin-table,.plugin-table tbody{display:block}.plugin-table thead{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}.plugin-table tr{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px 12px;padding:17px 0;border-bottom:1px solid #425449}.plugin-table tr:last-child{border:0}.plugin-table tbody th,.plugin-table td{width:auto;padding:0;border:0;min-width:0}.plugin-table tbody th{grid-column:1;grid-row:1}.plugin-table td:nth-child(2){grid-column:1 / -1;grid-row:2}.plugin-table td:nth-child(3){grid-column:2;grid-row:1;text-align:right}.plugin-table td:nth-child(4){grid-column:1 / -1;display:flex;align-items:center;gap:18px;margin-top:4px}.plugin-more{margin:0}.catalog-heading h2{font-size:25px}.plugin-detail-body{padding:0 18px 18px}}
</style>
