<script setup lang="ts">
import {computed, ref, watch} from "vue";
import {iconKindLabel, iconMatchesMonth, type IconLibraryCard} from "../icons/icon-library";

const props=defineProps<{items: IconLibraryCard[]; month?: number; loading?: boolean; error?: string}>();
const emit=defineEmits<{insert:[item:IconLibraryCard,caption:boolean];drag:[item:IconLibraryCard,caption:boolean,event:DragEvent];refresh:[]}>();
const query=ref("");const kind=ref("");const caption=ref(true);const page=ref(1);const pageSize=24;
const kinds=computed(()=>[...new Set(props.items.map(item=>item.kind))].sort());
const items=computed(()=>props.items.filter(item=>(!query.value||[item.title,item.history,...item.themes].join(" ").toLocaleLowerCase().includes(query.value.toLocaleLowerCase()))&&(!kind.value||item.kind===kind.value)).sort((a,b)=>Number(iconMatchesMonth(b,props.month))-Number(iconMatchesMonth(a,props.month))||a.title.localeCompare(b.title,"ru")));
const visibleItems=computed(()=>items.value.slice(0,page.value*pageSize));watch([query,kind,()=>props.items],()=>page.value=1);
</script>
<template><section class="icon-library-panel"><header><div><strong>Иконы</strong><span v-if="month">Сначала показаны празднования выбранного месяца</span></div><button type="button" @click="emit('refresh')">Обновить</button></header><div class="icon-library-panel__filters"><input v-model="query" type="search" placeholder="Поиск иконы" /><select v-model="kind"><option value="">Все разделы</option><option v-for="item in kinds" :key="item" :value="item">{{ iconKindLabel(item) }}</option></select><label><input v-model="caption" type="checkbox" /> Подпись под иконой</label></div><p v-if="loading">Загрузка икон…</p><p v-else-if="error" role="alert">{{ error }}</p><div v-else><p v-if="items.length" class="icon-library-panel__count">Показано {{ visibleItems.length }} из {{ items.length }}</p><div class="icon-library-panel__list"><article v-for="item in visibleItems" :key="item.id"><button type="button" draggable="true" :title="`Вставить или перетащить ${item.title}`" @dragstart="emit('drag',item,caption,$event)" @click="emit('insert',item,caption)"><img :src="item.images[0]?.imageUrl" :alt="item.title" /><span><strong>{{ item.title }}</strong><small>{{ iconKindLabel(item.kind) }}<template v-if="item.celebrations.length"> · {{ item.celebrations.map(day=>day.label).join(', ') }}</template></small></span></button></article><button v-if="visibleItems.length<items.length" type="button" @click="page++">Показать ещё {{ Math.min(pageSize,items.length-visibleItems.length) }} из {{ items.length }}</button><p v-if="!items.length">По выбранным условиям икон пока нет.</p></div></div></section></template>
