<script setup lang="ts">
import {computed, ref} from "vue";
import {iconKindLabel, iconMatchesMonth, type IconLibraryCard} from "../icons/icon-library";

const props=defineProps<{items: IconLibraryCard[]; month?: number; loading?: boolean; error?: string}>();
const emit=defineEmits<{insert:[item:IconLibraryCard,caption:boolean];refresh:[]}>();
const query=ref("");const kind=ref("");const theme=ref("");const caption=ref(true);
const kinds=computed(()=>[...new Set(props.items.map(item=>item.kind))].sort());
const themes=computed(()=>[...new Set(props.items.flatMap(item=>item.themes))].sort((a,b)=>a.localeCompare(b,"ru")));
const items=computed(()=>props.items.filter(item=>(!query.value||[item.title,item.history,...item.themes].join(" ").toLocaleLowerCase().includes(query.value.toLocaleLowerCase()))&&(!kind.value||item.kind===kind.value)&&(!theme.value||item.themes.includes(theme.value))).sort((a,b)=>Number(iconMatchesMonth(b,props.month))-Number(iconMatchesMonth(a,props.month))||a.title.localeCompare(b.title,"ru")));
</script>
<template><section class="icon-library-panel"><header><div><strong>Иконы</strong><span v-if="month">Сначала показаны празднования выбранного месяца</span></div><button type="button" @click="emit('refresh')">Обновить</button></header><div class="icon-library-panel__filters"><input v-model="query" type="search" placeholder="Поиск иконы" /><select v-model="kind"><option value="">Все разделы</option><option v-for="item in kinds" :key="item" :value="item">{{ iconKindLabel(item) }}</option></select><select v-model="theme"><option value="">Все темы</option><option v-for="item in themes" :key="item" :value="item">{{ item }}</option></select><label><input v-model="caption" type="checkbox" /> Подпись под иконой</label></div><p v-if="loading">Загрузка икон…</p><p v-else-if="error" role="alert">{{ error }}</p><div v-else class="icon-library-panel__list"><article v-for="item in items" :key="item.id"><button type="button" :title="`Вставить ${item.title}`" @click="emit('insert',item,caption)"><img :src="item.images[0]?.imageUrl" :alt="item.title" /><span><strong>{{ item.title }}</strong><small>{{ iconKindLabel(item.kind) }}<template v-if="item.celebrations.length"> · {{ item.celebrations.map(day=>day.label).join(', ') }}</template></small></span></button></article><p v-if="!items.length">По выбранным условиям икон пока нет.</p></div></section></template>
