<script setup lang="ts">
import {computed,onMounted,ref} from 'vue';
import {printRequest,printMoney,printOption,printStatus,printContactLabel,type PrintOrder,type PrintConfig} from '../printing/print-client';
const props=defineProps<{admin?:boolean}>();const orders=ref<PrintOrder[]>([]);const config=ref<PrintConfig>();const tab=ref('orders');const search=ref('');const error=ref('');const notice=ref('');const busy=ref(false);
const filtered=computed(()=>orders.value.filter(o=>`${o.id} ${o.email} ${o.name} ${o.contact.name}`.toLowerCase().includes(search.value.toLowerCase())));
const clients=computed(()=>{const rows=new Map<string,{email:string;name:string;count:number}>();for(const o of orders.value){const row=rows.get(o.owner)??{email:o.email,name:o.contact.name??'',count:0};row.count++;rows.set(o.owner,row);}return [...rows.values()];});
async function load(){busy.value=true;error.value='';try{orders.value=(await printRequest<{items:PrintOrder[]}>('orders','GET',undefined,props.admin)).items;if(props.admin)config.value=await printRequest<PrintConfig>('config','GET',undefined,true);}catch(e){error.value=String(e);}finally{busy.value=false;}}
async function save(){busy.value=true;error.value='';try{config.value=await printRequest<PrintConfig>('config','PUT',config.value,true);notice.value='Прайс сохранён. Новые цены действуют только на новые заявки.';}catch(e){error.value=String(e);}finally{busy.value=false;}}
async function action(o:PrintOrder,status:string){busy.value=true;error.value='';try{await printRequest(`orders/${o.id}/status`,'PUT',{status},true);await load();}catch(e){error.value=String(e);}finally{busy.value=false;}}
async function pay(o:PrintOrder){busy.value=true;error.value='';try{const r=await printRequest<{url:string}>(`orders/${o.id}/checkout`,'POST',{});if(!r.url.startsWith('https://checkout.stripe.com/'))throw new Error('Некорректная ссылка Stripe');window.location.assign(r.url);}catch(e){error.value=String(e);}finally{busy.value=false;}}
async function invoice(o:PrintOrder){busy.value=true;error.value='';try{const r=await printRequest<{url:string|null}>(`orders/${o.id}/invoice`,'GET',undefined,props.admin);if(!r.url?.startsWith('https://invoice.stripe.com/'))throw new Error('Счёт ещё не готов');window.location.assign(r.url);}catch(e){error.value=String(e);}finally{busy.value=false;}}
async function notify(o:PrintOrder){busy.value=true;error.value='';try{await printRequest(`orders/${o.id}/notify`,'POST',{},true);await load();}catch(e){error.value=String(e);}finally{busy.value=false;}}
function addService(){config.value?.services.push({id:'service-'+crypto.randomUUID().slice(0,8),name:'Новая услуга',price:0,enabled:false,perCopy:false});}
onMounted(load);
</script>
<template><section class="print-orders"><h2>{{admin?'Заказы печати':'Мои заказы'}}</h2>
  <nav><button :disabled="busy" @click="load">Обновить</button><template v-if="admin"><button @click="tab='orders'">Заказы</button><button @click="tab='clients'">Клиенты</button><button @click="tab='invoices'">Счета</button><button @click="tab='pricing'">Цены и Stripe</button></template></nav>
  <p v-if="error" role="alert">{{error}}</p><p role="status">{{notice}}</p>
  <template v-if="tab==='pricing'&&config"><p>Все суммы ниже — в минимальных единицах валюты: 100 = 1 EUR/USD/GBP. Цена порога — за целый календарь. Бумага и обложка — за экземпляр; единица расчёта услуги выбирается отдельно. Доставка — за заказ.</p>
    <label>Минимальный тираж<input v-model.number="config.minQuantity" type="number" min="1" /></label><p>Цена действует ровно на {{config.maxPages}} листов, включая обложку.</p><label v-for="(_,weight) in config.weights" :key="weight">Бумага {{weight}} г/м², доплата за экземпляр (центы)<input v-model.number="config.weights[weight]" type="number" min="0" /></label>
    <form @submit.prevent="save"><fieldset :disabled="busy"><label><input v-model="config.enabled" type="checkbox" /> Открыть приём заявок</label><label>Валюта<select v-model="config.currency"><option value="eur">EUR</option><option value="usd">USD</option><option value="gbp">GBP</option></select></label><label>Число листов в тарифе (включая обложку)<input v-model.number="config.maxPages" type="number" min="1" max="100" /></label><label>E-mail для заявок<input v-model="config.notificationEmail" type="email" /></label><label>Налоги / состав конечной цены<textarea v-model="config.taxNote" placeholder="Укажите реальное налоговое описание ваших цен" /></label><label>Условия печати и доставки<textarea v-model="config.terms" placeholder="Сроки, комплектация, плотность бумаги, переплёт, территория доставки, условия заказа" /></label>
    <h3>Цены по формату и тиражу</h3><div v-for="(tiers,format) in config.formats" :key="format"><h4>{{format}}</h4><div v-for="(tier,index) in tiers" :key="index" class="price-row"><label>От, шт.<input v-model.number="tier.min" type="number" min="1" max="10000" /></label><label>За календарь, центы<input v-model.number="tier.price" type="number" min="1" /></label><button type="button" @click="tiers.splice(index,1)">Убрать</button></div><button type="button" @click="tiers.push({min:tiers.length?tiers[tiers.length-1]!.min+50:1,price:0})">Добавить порог</button></div>
    <h3>Доплаты</h3><div v-for="key in (['paper','cover','delivery'] as const)" :key="key"><h4>{{{paper:'Бумага',cover:'Обложка',delivery:'Получение'}[key]}}</h4><label v-for="(_,option) in config[key]" :key="option">{{printOption(option)}}<input v-model.number="config[key][option]" type="number" min="0" /></label></div><button v-if="config.delivery.shipping===undefined" type="button" @click="config.delivery.shipping=0">Добавить доставку по фиксированной цене</button><button v-else type="button" @click="delete config.delivery.shipping">Отключить доставку</button>
    <h3>Услуги</h3><div v-for="(service,index) in config.services" :key="service.id" class="price-row"><input v-model="service.enabled" type="checkbox" /><label><input v-model="service.perCopy" type="checkbox" /> За экземпляр</label><input v-model="service.name" aria-label="Название услуги" /><input v-model.number="service.price" type="number" min="0" aria-label="Цена услуги, центы" /><button type="button" @click="config.services.splice(index,1)">Убрать</button></div><button type="button" @click="addService">Добавить услугу</button>
    <p>Stripe: {{config.stripeReady?'ключи настроены (платёж ещё нужно проверить)':'не настроен'}}. Секретные ключи задаются только на сервере: STRIPE_SECRET_KEY и STRIPE_WEBHOOK_SECRET.</p><p>Счёт создаёт Stripe после оплаты. Реквизиты продавца и налоговое оформление нужно настроить в Stripe; произвольный текст выше не настраивает налоги в счёте.</p><button>Сохранить прайс</button></fieldset></form>
  </template>
  <template v-else-if="tab==='clients'"><p v-for="client in clients" :key="client.email">{{client.name}} · {{client.email}} · Заказов: {{client.count}}</p><p v-if="!clients.length">Клиентов с заказами пока нет.</p></template>
  <template v-else><label>Поиск<input v-model="search" type="search" /></label><p v-if="!filtered.length">Заказов пока нет.</p>
    <article v-for="order in filtered.filter(o=>tab!=='invoices'||o.payment==='paid')" :key="order.id"><h3>{{order.name}} · {{order.quantity}} шт.</h3><p>{{order.id}} · {{new Date(order.createdAt).toLocaleString()}}</p><p>{{printStatus(order.status)}} · {{printStatus(order.payment)}} · {{printMoney(order.quote.total,order.quote.currency)}}</p><p>{{order.quote.format}} · {{order.quote.pages}} стр. · Бумага: {{printOption(order.paper)}} · Обложка: {{printOption(order.cover)}} · {{printOption(order.delivery)}}</p>
      <details><summary>Состав и контакты</summary><p v-for="(line,index) in order.quote.lines" :key="index">{{line.name}}: {{printMoney(line.total,order.quote.currency)}}</p><p>{{order.email}}</p><p v-for="(value,key) in order.contact" :key="key">{{printContactLabel(key)}}: {{value}}</p><p>{{order.quote.taxNote}}</p><p>{{order.quote.terms}}</p><p v-for="(event,index) in order.history" :key="index">{{event.at}} · {{printStatus(event.status)}}</p></details>
      <a :href="`/api/v1/${admin?'admin/':''}print/orders/${order.id}/pdf`" download>Скачать заказанный PDF</a>
      <button v-if="!admin&&order.status==='approved'&&order.payment==='unpaid'" :disabled="busy" @click="pay(order)">Оплатить через Stripe</button><button v-if="order.payment==='paid'" :disabled="busy" @click="invoice(order)">Открыть счёт Stripe</button>
      <template v-if="admin"><p>Уведомление: {{printStatus(order.notification)}} <button v-if="order.notification!=='sent'" :disabled="busy" @click="notify(order)">Повторить уведомление</button></p><template v-if="order.status==='requested'"><p>Перед подтверждением проверьте PDF: формат, число страниц, вылеты и возможность печати по указанной цене.</p><button :disabled="busy" @click="action(order,'approved')">PDF проверен — разрешить оплату</button><button :disabled="busy" @click="action(order,'rejected')">Отклонить</button></template><button v-if="order.status==='paid'" :disabled="busy" @click="action(order,'production')">Передать в печать</button><template v-if="order.status==='production'"><button :disabled="busy" @click="action(order,'shipped')">Отправлен</button><button :disabled="busy" @click="action(order,'completed')">Выдан / выполнен</button></template><button v-if="order.status==='shipped'" :disabled="busy" @click="action(order,'completed')">Выполнен</button></template>
    </article>
  </template>
</section></template>
<style scoped>
.print-orders button{padding:8px 12px;border:1px solid #8c784a;border-radius:5px;background:#394634;color:#f5ead1;cursor:pointer}.print-orders button:disabled{opacity:.5;cursor:default}.print-orders input:not([type=checkbox]),.print-orders textarea,.print-orders select{background:#18241e;border:1px solid #526458;border-radius:5px;color:#f3f2e7}.print-orders input:focus,.print-orders textarea:focus,.print-orders select:focus{outline:2px solid #b39859}
.print-orders nav,.price-row{display:flex;gap:10px;flex-wrap:wrap;align-items:end}.print-orders label{display:block;margin:8px 0}.print-orders input:not([type=checkbox]),.print-orders textarea,.print-orders select{display:block;padding:8px;max-width:100%}.print-orders textarea{width:100%;min-height:80px}.print-orders article{margin:14px 0;padding:18px;border:1px solid #65725c;border-radius:8px;background:#1e2d25}.print-orders article button{margin:8px}.print-orders fieldset{border:0;padding:0}.print-orders a{color:#e6cd8e}
</style>
