<script setup lang="ts">
import {onMounted,ref} from 'vue';
import {videoRequest,youtubeId,type VideoLesson} from '../content/video-lessons';
import {localizedPath} from '../navigation';
import {interfaceLanguage,INTERFACE_LANGUAGE_OPTIONS} from '../i18n/interface-language';
const items=ref<VideoLesson[]>([]),active=ref(''),error=ref(''),loading=ref(true);
onMounted(async()=>{try{items.value=(await videoRequest()).items;}catch(e){error.value=String(e);}finally{loading.value=false;}});
</script>
<template><main class="video-lessons"><header><a :href="localizedPath('/')">На главную</a><select v-model="interfaceLanguage" aria-label="Язык"><option v-for="language in INTERFACE_LANGUAGE_OPTIONS" :key="language.id" :value="language.id">{{language.nativeLabel}}</option></select></header><h1>Видеоуроки</h1><p>Короткие видео о работе в Календарной мастерской.</p><p v-if="loading" role="status">Загрузка…</p><p v-else-if="error" role="alert">{{error}}</p><p v-else-if="!items.length">Видеоуроки готовятся к публикации.</p><p v-else>Нажимая «Смотреть», вы загружаете проигрыватель и устанавливаете соединение с YouTube.</p><div class="video-lessons__list"><article v-for="(lesson,index) in items" :key="lesson.id"><h2 data-no-translate>{{index+1}}. {{lesson.title}}</h2><p v-if="lesson.duration" data-no-translate>{{lesson.duration}}</p><iframe v-if="active===lesson.id && youtubeId(lesson.url)" :src="`https://www.youtube-nocookie.com/embed/${youtubeId(lesson.url)}`" :title="lesson.title" allow="encrypted-media; picture-in-picture; fullscreen" allowfullscreen referrerpolicy="strict-origin-when-cross-origin" /><button v-else class="video-lessons__poster" type="button" @click="active=lesson.id"><span aria-hidden="true">▶</span> Смотреть</button></article></div></main></template>
<style scoped>
.video-lessons{max-width:1100px;margin:auto;padding:32px 24px 60px;box-sizing:border-box;color:#f4ead1}header{display:flex;justify-content:space-between;gap:16px}a{color:#e6cd8e}h1{font:46px Georgia,serif}h2{font-size:20px}.video-lessons__list{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,400px),1fr));gap:24px}article{padding:20px;background:#1c2923;border:1px solid #56604c;border-radius:8px}iframe,.video-lessons__poster{width:100%;aspect-ratio:16/9;border:0;border-radius:6px;box-sizing:border-box}.video-lessons__poster{display:flex;align-items:center;justify-content:center;gap:16px;color:#e6cd8e;background:linear-gradient(135deg,#293e30,#101a15);cursor:pointer;font-size:20px}.video-lessons__poster span{font-size:42px}button:focus-visible{outline:2px solid #e6cd8e;outline-offset:3px}select{max-width:180px}
</style>
